---
sidebar: sidebar 
permalink: express/express-c-series-aff220-design_technology_requirements.html 
keywords: express, requirements, technology, AFF A220, UCS C220 M5, Nexus 3172P switch, Virtual Interface Card, VIC 1387, C220 M5 Rack Server, CVR-QSFP-SFP10G adapter 
summary: FlexPod Express requiere una combinación de componentes de hardware y software que depende de la velocidad del hipervisor y de la red seleccionados. Además, FlexPod Express puede establecer los componentes de hardware necesarios para añadir nodos de hipervisor en unidades de dos. 
---
= Requisitos tecnológicos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


FlexPod Express requiere una combinación de componentes de hardware y software que depende de la velocidad del hipervisor y de la red seleccionados. Además, FlexPod Express puede establecer los componentes de hardware necesarios para añadir nodos de hipervisor en unidades de dos.



== Requisitos de hardware

Independientemente del hipervisor elegido, todas las configuraciones exprés de FlexPod utilizan el mismo hardware. Por lo tanto, aunque cambien los requisitos del negocio, cualquiera de los hipervisores puede ejecutarse en el mismo hardware de FlexPod Express.

La siguiente tabla enumera los componentes de hardware necesarios para todas las configuraciones exprés de FlexPod e implementar la solución. Los componentes de hardware que se usan en cualquier implementación particular de la solución pueden variar en función de las necesidades del cliente.

[cols="50,50"]
|===
| Hardware subyacente | Cantidad 


| Clúster de dos nodos AFF A220 | 1 


| Servidor Cisco UCS C220 M5 | 2 


| Switch Cisco Nexus 3172P | 2 


| Tarjeta de interfaz virtual (VIC) Cisco UCS 1387 para el servidor en rack Cisco UCS C220 M5 | 2 


| Adaptador Cisco CVR-QSFP-SFP10G | 4 
|===


== Requisitos de software

En las siguientes tablas, se enumeran los componentes de software necesarios para implementar las arquitecturas de la solución FlexPod Express.

La siguiente tabla enumera los requisitos de software para la implementación básica de FlexPod Express.

[cols="33,33,33"]
|===
| De NetApp | Versión | Detalles 


| Controladora de gestión integrada de Cisco (CIMC) | 3.1.3 | Para servidores en rack C220 M5 


| Cisco NX-OS | nxos.7.0.3.I7.5.bin | Para switches Cisco Nexus 3172P 


| ONTAP de NetApp | 9.4 | Para controladoras AFF A220 
|===
En la siguiente tabla se muestra el software necesario para todas las implementaciones de VMware vSphere en FlexPod Express.

[cols="50,50"]
|===
| De NetApp | Versión 


| Dispositivo VMware vCenter Server | 6.7 


| VMware vSphere ESXi | 6.7 


| Complemento VAAI de NetApp para ESXi | 1.1.2 
|===
link:express-c-series-aff220-design_design_choices.html["Siguiente: Opciones de diseño."]
