---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_netapp_aff_storage_deployment_procedure_@part_2@.html 
keywords: aff, storage, deployment, procedure, create, iscsi, igroups, ontap, san, boot 
summary: Para crear iGroups, ejecute los siguientes comandos desde la conexión SSH del nodo de gestión del clúster. 
---
= Procedimiento de puesta en marcha del almacenamiento AFF de NetApp (parte 2)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Configurar el almacenamiento DE arranque SAN de ONTAP



=== Cree iGroups iSCSI


NOTE: Para este paso, se necesitan los IQN de iniciadores iSCSI desde la configuración del servidor.

Para crear iGroups, ejecute los siguientes comandos desde la conexión SSH del nodo de gestión del clúster. Para ver los tres iGroups creados en este paso, ejecute el `igroup show` comando.

....
igroup create –vserver Infra-SVM –igroup VM-Host-Infra-A –protocol iscsi –ostype vmware –initiator <<var_vm_host_infra_a_iSCSI-A_vNIC_IQN>>,<<var_vm_host_infra_a_iSCSI-B_vNIC_IQN>>
igroup create –vserver Infra-SVM –igroup VM-Host-Infra-B –protocol iscsi –ostype vmware –initiator <<var_vm_host_infra_b_iSCSI-A_vNIC_IQN>>,<<var_vm_host_infra_b_iSCSI-B_vNIC_IQN>>
....

NOTE: Este paso se debe completar cuando se añaden servidores Cisco UCS C-Series adicionales.



== Asigne LUN de arranque a iGroups

....
To map boot LUNs to igroups, run the following commands from the cluster management SSH connection:
lun map –vserver Infra-SVM –volume esxi_boot –lun VM-Host-Infra-A –igroup VM-Host-Infra-A –lun-id 0
lun map –vserver Infra-SVM –volume esxi_boot –lun VM-Host-Infra-B –igroup VM-Host-Infra-B –lun-id 0
....

NOTE: Este paso se debe completar cuando se añaden servidores Cisco UCS C-Series adicionales.

link:express-c-series-c190-deploy_vmware_vsphere_6.7u2_deployment_procedure.html["Siguiente: Procedimiento de puesta en marcha de VMware vSphere 6.7U2."]
