---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_program_summary_overview.html 
keywords: fexpod, express, cisco, ucs, series, c, aff, c190, nva, deployment 
summary: El centro de datos de FlexPod y FlexPod Express proporcionan una configuración básica y cuentan con la flexibilidad necesaria para ajustar su tamaño y optimizarse con el objetivo de acomodar distintos casos de uso y requisitos. 
---
= NVA-1142-PUESTA en MARCHA: FlexPod Express con Cisco UCS C-Series y AFF C190 Series de NetApp: Puesta en marcha NVA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Savita Kumari, NetApp

Las tendencias del sector indican que se está produciendo una gran transformación de los centros de datos hacia la infraestructura compartida y el cloud computing. Además, las organizaciones buscan una solución sencilla y eficaz para oficinas remotas y sucursales que utilicen la tecnología con la que estén familiarizados en su centro de datos.

FlexPod® Express es una arquitectura de centro de datos diseñada previamente y basada en el Cisco Unified Computing System (Cisco UCS), la familia de switches Cisco Nexus y las tecnologías de almacenamiento de NetApp®. Los componentes de un sistema FlexPod Express se asemejan a los del centro de datos FlexPod, lo que permite sinergias de gestión en todo el entorno de infraestructura DE TI a una escala menor. FlexPod Datacenter y FlexPod Express son plataformas óptimas para virtualización y para sistemas operativos con configuración básica y cargas de trabajo empresariales.

El centro de datos de FlexPod y FlexPod Express proporcionan una configuración básica y cuentan con la flexibilidad necesaria para ajustar su tamaño y optimizarse con el objetivo de acomodar distintos casos de uso y requisitos. Los clientes existentes de FlexPod Datacenter pueden gestionar su sistema FlexPod Express con las herramientas a las que están acostumbrados. Los nuevos clientes de FlexPod Express pueden realizar fácilmente la transición a la gestión del centro de datos FlexPod a medida que crece su entorno.

FlexPod Express es una base de infraestructura óptima para oficinas remotas y sucursales y para pequeñas y medianas empresas. También es una solución óptima para los clientes que desean proporcionar infraestructura para cargas de trabajo dedicadas.

FlexPod Express proporciona una infraestructura fácil de gestionar que es adecuada para casi cualquier carga de trabajo.
