---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_deployment_procedures_overview.html 
keywords: configure,  express, flexpod, cisco, series, c190, deployment, overview 
summary: Este documento proporciona detalles para configurar un sistema FlexPod Express completamente redundante y de alta disponibilidad. Para reflejar esta redundancia, los componentes que se configuran en cada paso se denominan componente A o componente B. 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Este documento proporciona detalles para configurar un sistema FlexPod Express completamente redundante y de alta disponibilidad. Para reflejar esta redundancia, los componentes que se configuran en cada paso se denominan componente A o componente B. Por ejemplo, la controladora A y la controladora B identifican las dos controladoras de almacenamiento de NetApp que se aprovisionan en este documento. El switch A y el switch B identifican un par de switches Cisco Nexus.

Además, en este documento se describen los pasos para aprovisionar varios hosts de Cisco UCS, que se identifican secuencialmente como servidor A, servidor B, etc.

Para indicar que debe incluir la información pertinente a su entorno en un paso, `\<<text>>` aparece como parte de la estructura de comandos. Consulte el siguiente ejemplo de `vlan create` comando:

....
Controller01> network port vlan create –node <<var_nodeA>> -vlan-name <<var_vlan-name>>
....
Este documento permite configurar completamente el entorno de FlexPod Express. En este proceso, varios pasos requieren que inserte convenciones de nomenclatura específicas del cliente, direcciones IP y esquemas de red de área local virtual (VLAN). En la siguiente tabla se describen las VLAN necesarias para la implementación, tal y como se describe en esta guía. Esta tabla se puede completar en función de las variables específicas del sitio y se puede utilizar para implementar los pasos de configuración del documento.


NOTE: Si se utilizan VLAN de gestión fuera de banda y en banda independientes, debe crear una ruta de capa- 3 entre ellas. Para esta validación, se utilizó una VLAN de gestión común.

|===
| Nombre de la VLAN | Propósito de VLAN | ID DE VLAN |  


| VLAN de gestión | VLAN para interfaces de gestión | 3437 | VSwitch0 


| VLAN NFS | VLAN para tráfico NFS | 3438 | VSwitch0 


| VLAN de VMware vMotion | VLAN designada para mover máquinas virtuales (VM) de un host físico a otro | 3441 | VSwitch0 


| VLAN de tráfico de la máquina virtual | VLAN para tráfico de aplicaciones de equipos virtuales | 3442 | VSwitch0 


| ISCSI-A-VLAN | VLAN para tráfico iSCSI en la estructura A | 3439 | IScsiBootvSwitch 


| ISCSI-B-VLAN | VLAN para tráfico iSCSI en la estructura B | 3440 | IScsiBootvSwitch 


| VLAN nativa | VLAN a la que se asignan tramas no etiquetadas | 2 |  
|===
Los números VLAN son necesarios en toda la configuración de FlexPod Express. Las VLAN se denominan `\<<var_xxxx_vlan>>`, donde `xxxx` Es la finalidad de la VLAN (como iSCSI-A).

En esta validación se han creado dos vSwitch.

En la siguiente tabla se enumeran los vSwitch de la solución.

|===
| Nombre de vSwitch | Adaptadores activos | Puertos | MTU | Balanceo de carga 


| VSwitch0 | Vmnic2, vmnic4 | predeterminado (120) | 9000 | Ruta basada en hash IP 


| IScsiBootvSwitch | Vmnic3, vmnic5 | predeterminado (120) | 9000 | Ruta basada en el identificador de puerto virtual de origen. 
|===

NOTE: El método hash IP del equilibrio de carga requiere la configuración adecuada para el conmutador físico subyacente mediante SRC-DST-IP EtherChannel con un puerto-canal estático (modo activado). En caso de que se produzca una conectividad intermitente debido a una posible configuración incorrecta del switch, cierre temporalmente uno de los dos puertos de enlace ascendente asociados en el switch de Cisco para restaurar la comunicación con el puerto vmkernel de gestión de ESXi mientras se solucionan los problemas de la configuración del canal de puertos.

La siguiente tabla enumera las máquinas virtuales de VMware que se crean.

|===
| Descripción de la máquina virtual | Nombre de host 


| Servidor VMware vCenter | FlexPod-VCSA 


| Consola de almacenamiento virtual | FlexPod VSC 
|===