---
settings:
  name: FlexPod
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Documentación de las soluciones FlexPod
    url: "/index.html"
  - section: fp-def
  - section: flexpod-dc
  - section: hybrid-cloud
  - section: ent-db
  - section: healthcare
  - section: vdi
  - section: modern-apps
  - section: express
  - section: security
  - section: ontap-connector-for-intersight
  - section: infrastructure
homepage:
  tiles:
  - title: 'FlexPod: Comience aquí'
    links:
    - title: Novedades
      summary: ''
      url: https://fieldportal.netapp.com/content/1668183
    - title: Vídeos y demostraciones
      summary: ''
      url: https://tv.netapp.com/search?q=FlexPod
    - title: Blogs
      summary: ''
      url: https://blog.netapp.com/tag/Flexpod/
  - title: IA y análisis de datos modernos con FlexPod
    links:
    - title: Novedades
      summary: ''
      url: https://www.flexpod.com/solutions/use-cases/machine-learning/
    - title: Vídeos y demostraciones
      summary: ''
      url: https://tv.netapp.com/search?q=FlexPod%20AI
    - title: Blogs
      summary: ''
      url: https://blog.netapp.com/tag/Flexpod/
  - title: Aplicaciones empresariales y bases de datos empresariales de FlexPod
    links:
    - title: Vídeos y demostraciones
      summary: ''
      url: https://tv.netapp.com/search?q=FlexPod%20SAP
    - title: Blogs
      summary: ''
      url: https://blog.netapp.com/tag/Flexpod/
  - title: Cloud híbrido con FlexPod
    links:
    - title: Novedades
      summary: ''
      url: https://flexpod.com/solutions/use-cases/hybrid-cloud/
    - title: Vídeos y demostraciones
      summary: ''
      url: https://tv.netapp.com/search?q=FlexPod%20Hybrid%20Cloud
    - title: Blogs
      summary: ''
      url: https://blog.netapp.com/tag/Flexpod/
  - title: FlexPod para VDI
    links:
    - title: Novedades
      summary: ''
      url: https://www.flexpod.com/solutions/use-cases/virtual-desktop-infrastructure/
    - title: Vídeos y demostraciones
      summary: ''
      url: https://tv.netapp.com/search?q=FlexPod%20VDI
    - title: Blogs
      summary: ''
      url: https://blog.netapp.com/tag/Flexpod/
  - title: Cuidado de la salud con FlexPod
    links:
    - title: Novedades
      summary: ''
      url: https://flexpod.com/solutions/verticals/healthcare/
    - title: Vídeos y demostraciones
      summary: ''
      url: https://tv.netapp.com/search?q=FlexPod%20Healthcare
    - title: Blogs
      summary: ''
      url: https://blog.netapp.com/tag/Healthcare/
