---
settings:
  name: FlexPod
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de las soluciones FlexPod
    url: "/index.html"
  - section: fp-def
  - section: flexpod-dc
  - section: hybrid-cloud
  - section: ent-db
  - section: healthcare
  - section: vdi
  - section: modern-apps
  - section: express
  - section: security
  - section: ontap-connector-for-intersight
  - section: infrastructure
  - title: Avisos legales
    url: "/legal-notices.html"
