---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, datacenter, netapp, cisco, ucs, disk shelves 
summary: Esta sección describe los requisitos de alimentación y las directrices de cableado de los bastidores de discos para un diseño de FlexPod Datacenter. 
---
= Directrices sobre alimentación eléctrica y cableado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta sección describe los requisitos de alimentación eléctrica y las directrices de cableado para un diseño de FlexPod Datacenter.



[[power-requirements]]
== Requisitos de alimentación

Los requisitos de alimentación del centro de datos de FlexPod difieren en función de la ubicación en la que se ha instalado la configuración del centro de datos de FlexPod.

Para obtener más datos acerca de la potencia máxima necesaria y para obtener otra información detallada sobre la alimentación, consulte las especificaciones técnicas de cada componente de hardware enumerado en la sección link:dc-tech-spec_technical_specifications_and_references.html["Especificaciones técnicas y referencias: Componentes de hardware"].

Para obtener información detallada sobre el consumo energético de Cisco UCS, consulta la  https://ucspowercalculator.cisco.com/["Calculadora de potencia de Cisco UCS"^].

Para consultar los datos de alimentación del controlador de almacenamiento de NetApp, consulta el https://hwu.netapp.com/["Hardware Universe de NetApp"^]. En *Plataformas*, selecciona la plataforma de almacenamiento que quieres usar (por ejemplo, AFF A90), selecciona la versión de ONTAP y luego haz clic en *Mostrar resultados*. Los datos sobre los cables de alimentación aparecen en la sección *Cables de alimentación compatibles*. Para detalles sobre tamaño, peso, potencia, etc., consulta la sección *Tamaño, peso, ruido y potencia*.



[[cabling-guidelines]]
== Directrices de cableado

Esta sección proporciona directrices generales de cableado para un diseño de FlexPod Datacenter.

* Asegúrate de que las conexiones de cómputo y almacenamiento tengan redundancia.
* La velocidad de las conexiones debe ser compatible con los componentes conectados.
* Consulta la sección link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod Datacenter topologías"^] para obtener más directrices de cableado para topologías específicas.


La siguiente tabla ofrece directrices de cableado para las unidades de disco NetApp que pueden utilizarse en un diseño de FlexPod Datacenter.

|===


| Bandeja de discos | Directrices de cableado 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["Normas de cableado SAS"^] 


| DS224C 


| DS460C 


| NS224 .3+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Requisitos y prácticas recomendadas para los shelf NS224 y NX224"^] 


| NS224 con NSM100B 


| NX224 
|===