---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_flexpod_platforms.html 
keywords: flexpod, platforms, datacenter, technical, specifications, express, infrastructure 
summary:  
---
= Plataformas FlexPod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen dos plataformas FlexPod:

* *FlexPod Datacenter.* Esta plataforma es una infraestructura de centro de datos altamente escalable adecuada para aplicaciones y cargas de trabajo empresariales, virtualización, AI/ML, bases de datos, SAP HANA, infraestructura de escritorio virtual (VDI) y cargas de trabajo de nube pública, privada e híbrida.
* *FlexPod Express.* Esta plataforma es una infraestructura convergente compacta que está pensada para casos de uso de oficinas remotas y extremo. FlexPod Express tiene sus propias especificaciones, que están documentadas en la https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_overview.html["Especificaciones técnicas de FlexPod Express"^].


Este documento proporciona las especificaciones técnicas para la plataforma del centro de datos FlexPod.
