---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: Una configuración de FlexPod Datacenter tiene requisitos mínimos de hardware, incluidos, entre otros, switches, interconexiones de estructura, servidores y controladoras de almacenamiento de NetApp. 
---
= Requisitos mínimos de hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Una configuración de FlexPod Datacenter tiene requisitos mínimos de hardware, incluidos, entre otros, switches, interconexiones de estructura, servidores y controladoras de almacenamiento de NetApp.

Una configuración FlexPod tiene los siguientes requisitos mínimos de hardware:

* Dos conmutadores Cisco Nexus en una configuración de redundancia. Esta configuración puede consistir en dos conmutadores redundantes de la serie Cisco Nexus 9000 mencionada anteriormente. Los dos conmutadores deben ser del mismo modelo y deben estar configurados en el mismo modo de funcionamiento.



NOTE: Si vas a implementar una arquitectura ACI, debes cumplir con los siguientes requisitos adicionales: * Implementa los switches Cisco Nexus 9000 Series en una topología leaf-spine. * Usa tres Cisco Application Policy Infrastructure Controllers (APICs).

* Dos Cisco UCS Fabric Interconnects de las series 6400, 6500 o 6600 en una configuración redundante, si usas los UCS C-Series Rack Servers o los X-Series Modular systems.
* Dos servidores en rack Cisco UCS C-Series con conectividad FI y configuración gestionada por Intersight (IMM), o el Cisco UCS X-Series Direct con Cisco IMM, o el Cisco UCS X-Series Modular con configuración gestionada por Cisco Intersight (IMM).



NOTE: Si utilizas los servidores en rack UCS sin conectividad FI, puedes usar CIMC o el modo autónomo de Intersight para la gestión.

* Dos controladoras NetApp AFF, NetApp ASA o NetApp FAS en una configuración de par de alta disponibilidad (HA) implementada como un clúster de dos nodos. Si usas NetApp AFX, se requiere un mínimo de cuatro controladoras NetApp AFX y deben implementarse como un clúster HA de cuatro nodos junto con un par de switches de interconexión de clúster.
* Se requiere como mínimo un bastidor de discos NetApp para los controladores de almacenamiento que no tienen un bastidor de discos integrado.

