---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_components.html 
keywords: cisco, components, ucs, fabric, interconnect, server, rack, apic, nexus, software, support, mds, x-series-modular, x-series-direct 
summary: Cisco ha contribuido de manera significativa al diseño y la arquitectura de FlexPod, abarcando tanto la capa de computación como la de redes de la solución. En esta sección se describen las opciones de Cisco UCS y Cisco Nexus disponibles para FlexPod. 
---
= Componentes de Cisco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cisco ha contribuido de manera significativa al diseño y la arquitectura de FlexPod, abarcando tanto la capa de computación como la de redes de la solución. Esta sección describe las opciones de Cisco UCS, Nexus y MDS que están disponibles para FlexPod.



[[cisco-ucs-fabric-interconnect-options]]
== Opciones de interconexión de estructura Cisco UCS

Se necesitan interconexiones de estructura redundantes en la arquitectura de FlexPod. Cuando se añaden varios chasis Cisco UCS a un par de interconexiones de estructura, recuerde que el número máximo de chasis de un entorno está determinado por el límite de arquitectura y de puerto.

Los números de pieza que aparecen en la siguiente tabla corresponden a los fabric interconnects base. No incluyen la fuente de alimentación (PSU) ni los módulos SFP+, QSFP+ o de expansión.

|===
| Interconexión de estructura Cisco UCS | Número de pieza | Especificaciones técnicas 


| Cisco UCS 6664 | UCS-FI-6664-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-6600-series-fabric-interconnect-specsheet.pdf["Cisco UCS 6600 Series Fabric Interconnect"] 


| Cisco UCS 6652 | UCS-FI-6652-U 


| Cisco UCS 6536 | UCSX-FI-6536-U | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-6536-fabric-interconnect-spec-sheet.pdf["Cisco UCS 6536 Fabric Interconnect"] 


| Cisco UCS 6454 | UCS-FI-6454-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/6400-specsheet.pdf["Cisco UCS 6400 Series Fabric Interconnect"] 


| Cisco UCS 64108 | UCS-FI-64108-U 


| Fabric Interconnect UCS 9108 100G (Cisco UCS X-Series Direct) | UCSX-S9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Cisco UCS 9108 Fabric Interconnect"] 
|===


[[cisco-ucs-x-series-chassis-option]]
== Opción de chasis Cisco UCS X-Series

Para usar nodos de computación Cisco UCS X-Series, debe tener un chasis Cisco UCS X-Series. En la siguiente tabla se describe la opción del chasis Cisco UCS X-Series.

|===
| Blade Cisco UCS serie X | Número de pieza | Especificaciones técnicas 


| Chasis Cisco UCS X9508 | UCSX-9508 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html?ccid=cc002456&oid=dstcsm026317["Chasis Cisco UCS X9508"] 
|===
Cada chasis Cisco UCS 9508 debe tener dos módulos de estructura inteligente (IFMS) Cisco UCS 9108 para proporcionar conectividad redundante a las interconexiones de estructura.



[[cisco-ucs-x-series-device-options]]
== Opciones de dispositivos Cisco UCS X-Series

Los nodos de computación Cisco UCS X-Series están disponibles con diversas opciones de CPU, memoria e I/O. Los números de pieza enumerados en la siguiente tabla son para el nodo base. No incluyen la CPU, la memoria, las unidades ni las tarjetas adaptadoras mezzanine. La arquitectura FlexPod admite varias opciones de configuración.

|===
| Nodos de computación Cisco UCS X-Series | Número de pieza | Especificaciones técnicas 


| Cisco UCS X210c M7 | UCSX-210C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Nodo de computación Cisco UCS X210c M7"] 


| Cisco UCS X210c M8 | UCSX-210C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Nodo de computación Cisco UCS X210c M8"] 


| Cisco UCS X215c M8 | UCSX-215C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Nodo de computación Cisco UCS X215c M8"] 


| Cisco UCS X410c M7 | UCSX-410C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Nodo de computación Cisco UCS X410c M7"] 


| Cisco UCS X410c M8 | UCSX-410C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Nodo de computación Cisco UCS X410c M8"] 
|===
En la siguiente tabla se enumeran los nodos PCI Express disponibles para el chasis Cisco UCS X-Series.

|===
| Nodos PCIe de la serie X de Cisco UCS | Número de pieza | Especificaciones técnicas 


| Nodo PCIe Cisco UCS X580p | UCSX-580P-U | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x580p-pcie-node-ds.html["Nodo PCIe Cisco UCS X580p"] 


| Nodo PCIe Cisco UCS X440p | UCSX-440P | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x440p-pcle-node-ds.html["Nodo PCIe Cisco UCS X440p"] 
|===
La tabla siguiente muestra los módulos X-Fabric disponibles para el chasis Cisco UCS X-Series.

|===
| Módulos X-Fabric de la serie X de Cisco UCS | Número de pieza | Especificaciones técnicas 


| Módulo de tejido inteligente Cisco UCS 9108 | UCSX-I-9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-9108-100g-intelligent-fabric-module-spec-sheet.pdf["Módulo de tejido inteligente Cisco UCS 9108"] 


| Módulo Cisco UCS X9516 X-Fabric | UCSX-FS-9516 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-9516-x-fabric-module-ds.html["Módulo Cisco UCS X9516 X-Fabric"] 


| Módulo Cisco UCS X9416 X-Fabric | UCSX-F-9416 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/solution-overview-c22-2432175.html?ccid=cc002456&oid=sowcsm025665["Módulo Cisco UCS X9416 X-Fabric"] 
|===


[[cisco-ucs-x-series-modular-system]]
== Sistema modular Cisco UCS X-Series

El sistema modular Cisco UCS X-Series comienza con el chasis de servidor Cisco UCS X9508, diseñado para ser adaptable y preparado para el futuro. El chasis tiene una estructura Ethernet unificada con los módulos Cisco UCS Intelligent Fabric y la tecnología Cisco UCS X-Fabric para otras tecnologías. En la parte superior trasera del chasis hay dos módulos de estructura inteligente que conectan el chasis a los Cisco UCS 6400, 6500 y UCS 6600 Series Fabric Interconnects.

Para obtener una visión general rápida de las capacidades y características de la serie X de Cisco UCS, consulta link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-modular-system-aag.html["Resumen del sistema modular Cisco UCS X-Series"^].

Los nodos de cálculo Cisco UCS X215c M8, Cisco UCS X210c y Cisco UCS X410c proporcionan las funcionalidades tanto de los servidores blade como de los servidores en rack, al ofrecer densidad de cálculo, capacidad de almacenamiento y capacidad de ampliación en un único formato.

El nodo PCIe Cisco UCS X440p admite la incorporación de GPU con PCIe Gen 4.0 mediante el módulo Cisco UCS X9416 X-Fabric. El nodo PCIe Cisco UCS X580p admite la incorporación de GPU con PCIe Gen 5.0 mediante el módulo Cisco UCS X9516 X-Fabric.

Consulta las especificaciones técnicas de cada uno de estos componentes en las secciones anteriores para obtener más información sobre los componentes de la solución Cisco UCS X-Series Modular System.


NOTE: Consulta el siguiente enlace para ver las especificaciones técnicas completas del sistema modular Cisco UCS X-Series: link:https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-x-series-modular-system/datasheet-listing.html["Sistema modular Cisco UCS X-Series"^]



[[cisco-ucs-x-series-direct-options]]
== Opciones de Cisco UCS X-Series Direct

Cisco UCS X-Series Direct es una nueva arquitectura que integra un par de Cisco UCS Fabric Interconnect 9108 100G con Cisco UCS X9508 Chassis y Cisco UCS X-Series Compute nodes para ofrecer la solución UCS X-Series Direct.

Para obtener una visión general rápida de las capacidades y características de la serie X de Cisco UCS, consulta link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-aag.html["Cisco UCS X-Series Direct de un vistazo"^].

Cisco UCS X-Series Direct consta de los siguientes componentes:

* Cisco UCS 9108 100G Fabric Interconnect
* Chasis Cisco UCS X9508
* Nodos de cómputo Cisco UCS X-Series
* Componentes opcionales:
+
** Nodos PCIe y módulo X-Fabric
** Segundo chasis Cisco UCS X9508 con nodos de cómputo X-Series, módulos Intelligent Fabric Cisco UCS 9108-100G y hasta cuatro servidores en rack C-Series




Consulta las especificaciones técnicas de cada uno de estos componentes en las secciones anteriores para obtener más información sobre los componentes de la solución Cisco UCS X-Series Direct.


NOTE: Consulta el siguiente enlace para ver las especificaciones técnicas completas de Cisco UCS X-Series Direct: https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-ds.html["Ficha técnica de Cisco UCS X-Series Direct"].



[[cisco-ucs-c-series-rack-server-options]]
== Opciones de servidores en rack de la serie C de Cisco UCS

Los servidores en rack Cisco UCS de la serie C están disponibles en versiones de una, dos y cuatro unidades rack (RU), con diversas opciones de CPU, memoria y E/S. Los números de pieza que figuran en la segunda tabla a continuación corresponden al servidor base. No incluyen CPU, memoria, unidades de disco ni tarjetas Peripheral Component Interconnect Express (PCIe). Hay disponibles múltiples opciones de configuración y son compatibles con la arquitectura FlexPod.

En la siguiente tabla se enumeran las opciones del servidor en rack Cisco UCS C-Series.

|===
| Servidor en rack Cisco UCS C-Series | Número de pieza | Especificaciones técnicas 


| Cisco UCS C220 M7 | UCSC-C220-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Servidor en rack Cisco UCS C220 M7"] 


| Cisco UCS C220 M8 | UCSC-C220-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Servidor en rack Cisco UCS C220 M8"] 


| Cisco UCS C225 M8 | UCSC-C225-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html["Servidor en rack Cisco UCS C225 M8"] 


| Cisco UCS C240 M7 | UCSC-C240-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Servidor en rack Cisco UCS C240 M7"] 


| Cisco UCS C240 M8 | UCSC-C240-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Servidor en rack Cisco UCS C240 M8"] 


| Cisco UCS C245 M8 | UCSC-C245-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Servidor en rack Cisco UCS C245 M8"] 
|===
En la siguiente tabla se enumeran los servidores en rack de la serie C de Cisco UCS optimizados para casos de uso de IA:

|===
| Servidor de montaje en rack Cisco UCS C-Series | Número de pieza | Especificaciones técnicas 


| Cisco UCS C845A M8 | UCSC-C845A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c845a-m8-rack-server-ds.html["Servidor en rack Cisco UCS C845A M8"] 


| Cisco UCS C880A M8 | UCSC-C880A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c880a-m8-rack-server-ds.html["Servidor en rack Cisco UCS C880A M8"] 
|===
Las generaciones anteriores de servidores Cisco UCS C-Series pueden usarse en la arquitectura FlexPod si son compatibles con https://ucshcltool.cloudapps.cisco.com/public/["Lista de compatibilidad de hardware y software de Cisco UCS"^].



[[cisco-nexus-9000-series-switch-options]]
== Opciones de switch Cisco Nexus serie 9000

Se requieren conmutadores redundantes Cisco Nexus 9000 Series en la arquitectura FlexPod. Los números de parte que aparecen en la tabla a continuación son para los chasis Cisco Nexus 9000 Series; no incluyen módulos SFP ni módulos Ethernet.

|===
| Conmutador Cisco Nexus - Fixed | Especificaciones técnicas 


| Switch Cisco Nexus 9200 series | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switches Cisco Nexus serie 9200"] 


| Switch Cisco Nexus 9300 series | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Switches Cisco Nexus serie 9300"] 
|===
|===
| Conmutador Cisco Nexus - Modular | Especificaciones técnicas 


| Switch Cisco Nexus 9400 series | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9400-series-switches-ds.html?ccid=cc002962&oid=dstdnc029385["Switches de la serie Cisco Nexus 9400"] 


| Switch Cisco Nexus 9500 series | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729404.html["Switches Cisco Nexus serie 9500"] 


| Switch Cisco Nexus 9800 series | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9800-series-switches-ds.html?ccid=cc002962&oid=dstdnc029386["Switches de la serie Cisco Nexus 9800"] 
|===


[[cisco-apic-options]]
== Opciones APIC de Cisco

Cisco APIC es el principal componente arquitectónico de Cisco ACI. Es el punto unificado de automatización y gestión para la estructura de Cisco ACI.

Para obtener más información sobre las especificaciones de los productos APIC, consulta la tabla 1 hasta la tabla 3 en https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-739715.html["Hoja de datos del controlador de infraestructura de políticas de aplicaciones de Cisco"^].



[[cisco-mds-options]]
== Opciones de Cisco MDS

Aunque los conmutadores Cisco MDS son un elemento opcional de la arquitectura FlexPod, las implementaciones que utilizan conectividad SAN Fibre Channel para un acceso al almacenamiento de alto rendimiento deben implementar estructuras de conmutadores Cisco MDS redundantes para ofrecer una infraestructura SAN de alta disponibilidad. La tabla siguiente enumera los conmutadores Cisco MDS compatibles. Consulta https://imt.netapp.com["IMT de NetApp"^] y https://ucshcltool.cloudapps.cisco.com/public/["Lista de compatibilidad de hardware y software de Cisco"^] para obtener una lista completa de los conmutadores SAN compatibles.

|===
| Conmutador Cisco MDS | Descripción 


| Switches de fabric multicapa Cisco MDS 9100 | http://www.cisco.com/c/en/us/products/storage-networking/mds-9100-series-multilayer-fabric-switches/datasheet-listing.html["Switches Cisco MDS 9100 Series"] 


| Conmutadores multiservicio Cisco MDS 9200 | https://www.cisco.com/c/en/us/products/storage-networking/mds-9200-series-multiservice-switches/datasheet-listing.html["Conmutadores Cisco MDS 9200 Series"] 


| Switches de fabric multicapa Cisco MDS 9300 | https://www.cisco.com/c/en/us/products/storage-networking/mds-9300-series-multilayer-fabric-switches/datasheet-listing.html["Switches Cisco MDS 9300 Series"] 


| Cisco MDS 9700 Multilayer Directors | http://www.cisco.com/c/en/us/products/storage-networking/mds-9700-series-multilayer-directors/datasheet-listing.html["Conmutadores Cisco MDS 9700 Series"] 
|===


[[cisco-support-licensing-options]]
== Opciones de licencias de soporte de Cisco


NOTE: Se recomienda confirmar los requisitos de licencia con tu representante de ventas de Cisco o NetApp antes de hacer el pedido.

link:https://www.cisco.com/c/dam/en_us/about/doing_business/legal/service_descriptions/docs/solution-support-smart-total-care.pdf["Cisco Solution Support"^] es una oferta de soporte técnico que se aplica a las soluciones de Cisco que incluyen tanto hardware como software, ya sea exclusivamente de Cisco o de Cisco y de Solution Support Alliance Partners, y que están compuestas únicamente por productos de Cisco y productos proporcionados por terceros (Solution Support Alliance Partner(s)).

Cisco ofrece soporte para entornos complejos de los clientes a través de su link:https://www.cisco.com/c/en/us/support/web/tac/technical-services-resource-guide.html["Centro de Asistencia Técnica"]. Cisco Solution Support permite a los clientes acceder a un equipo de ingenieros de TAC, que actúan como punto de contacto principal para los problemas que surjan en la solución, además de proporcionar soporte para el hardware y el software que la componen.

Cisco aprovecha el marco link:https://www.tsanet.org/cisco-tsanet-case-study/["Programa de partners de TSANet"^] para incorporar a los Solution Support Partners a un grupo privado en el sistema TSANet Connect. TSANet Connect ofrece un método coherente para que los ingenieros de soporte colaboren con los equipos técnicos de los Partners, asegurando una comunicación eficiente y una resolución acelerada de problemas sin la fricción que causan los intentos informales de trabajar con partners.
