---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_netapp_ontap.html 
keywords: ontap, aff, asa, fas, afx, system, datacenter, technical, specifications, flexpod, software 
summary: El software NetApp ONTAP está instalado en cada sistema NetApp AFF, ASA, FAS y AFX. FlexPod está validado con el software ONTAP, proporcionando una arquitectura de almacenamiento altamente escalable que permite operaciones sin interrupciones, actualizaciones sin interrupciones y una infraestructura de datos ágil. 
---
= ONTAP de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El software NetApp ONTAP es el sistema operativo que se ejecuta en los sistemas de almacenamiento AFF, ASA, FAS y AFX. ONTAP ofrece una arquitectura de almacenamiento altamente escalable que permite operaciones sin interrupciones, actualizaciones sin interrupciones y una infraestructura de datos ágil. Con el modelo de licencia ONTAP One, todos los servicios de datos empresariales se incluyen en un solo paquete, lo que simplifica la implementación y la gestión, y proporciona acceso completo a funciones avanzadas. ONTAP ofrece una sólida protección de datos mediante tecnologías como SnapMirror para replicación y recuperación ante desastres, así como SnapCenter para backup y restauración consistente con las aplicaciones. También incorpora funciones de seguridad integradas, como la Protección Autónoma contra Ransomware y el cifrado, para proteger los datos frente a amenazas modernas. Además, ONTAP permite una integración fluida con la nube híbrida gracias a capacidades como SnapMirror Cloud y replicación basada en S3, lo que permite la movilidad de datos entre entornos locales y en la nube, manteniendo la coherencia y el control.

Para obtener más información sobre ONTAP, consulta la  https://www.netapp.com/ontap-data-management-software/["Software de gestión de datos ONTAP"^] página del producto.
