---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_supported_versus_validated_flexpod_configurations.html 
keywords: flexpod, architecture, supported, validated, configurations, hardware, software 
summary: La arquitectura de FlexPod está definida por el conjunto de reglas que se describen en este documento. 
---
= Compatible con configuraciones de FlexPod validadas frente a las validadas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La arquitectura de FlexPod está definida por el conjunto de reglas que se describen en este documento. Los componentes de hardware y las configuraciones de software deben ser compatibles con https://ucshcltool.cloudapps.cisco.com/public/["Lista de compatibilidad de hardware y software de Cisco UCS"^] y la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^].

Cada Cisco Validated Design (CVD) o NetApp Verified Architecture (NVA) es una posible configuración de FlexPod. Cisco y NetApp documentan estas combinaciones de configuración y las validan mediante una exhaustiva prueba de extremo a extremo. Las instalaciones de FlexPod que no se puedan implementar con estas configuraciones son totalmente compatibles si siguen las directrices de este documento y si todos los componentes aparecen como compatibles en la lista de compatibilidad de hardware y software de Cisco UCS y NetApp http://mysupport.netapp.com/matrix["IMT"^].

Por ejemplo, añadir más controladoras de almacenamiento o servidores Cisco UCS y actualizar software a versiones más nuevas es totalmente compatible si el software, el hardware y las configuraciones cumplen las directrices definidas en este documento.
