---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, cisco, ucs, fabric, interconnect, uplink, direct, san 
summary: A continuación se enumeran los requisitos de conectividad para la configuración de FlexPod. 
---
= Requisitos de conectividad
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Una configuración FlexPod tiene los siguientes requisitos de conectividad:

* Se requiere una red de gestión fuera de banda de 1 Gb Ethernet independiente para todos los componentes.
* NetApp recomienda que habilite la compatibilidad con las tramas gigantes en todo el entorno, pero no es necesario.
* Los puertos de dispositivo Cisco UCS Fabric Interconnect independientes se recomiendan solo para conexiones iSCSI. Cuando se usan conexiones NAS con puertos de dispositivo, se requieren switches Nexus / compatibles adicionales para ciertos escenarios de fallo.
* No se puede colocar ningún equipo adicional en línea entre los componentes principales de FlexPod.


Conexiones de enlace ascendente:

* Los puertos de los controladores de almacenamiento NetApp deben conectarse a los switches Cisco Nexus 9000 Series para habilitar la compatibilidad con los virtual port channels (vPC).
* Se requieren vPCs desde los conmutadores Cisco Nexus 9000 Series Switches hasta los controladores de almacenamiento NetApp.
* Se requieren vPC desde los switches Cisco Nexus 9000 Series hasta los fabric interconnects.
* Se requieren al menos dos conexiones para un VPC. Es posible aumentar el número de conexiones dentro de un VPC en función de los requisitos de carga de las aplicaciones y de rendimiento.


Conexiones directas:

* NetApp Los puertos del controlador de almacenamiento que están conectados directamente a las interconexiones de la estructura (como en el caso de X-Series Direct) pueden agruparse para habilitar un canal de puertos. vPC no es compatible con esta configuración.
* Se recomiendan canales de puertos FCoE para diseños FCoE integrales.


Arranque SAN:

* Las soluciones FlexPod están diseñadas en torno a una arquitectura DE arranque SAN mediante los protocolos iSCSI, FC o FCoE. El uso de tecnologías "arranque desde SAN" proporciona la configuración más flexible de la infraestructura del centro de datos y permite disponer de las completas funciones de cada componente de la infraestructura. Aunque el arranque desde SAN es la configuración más eficiente, el arranque desde el almacenamiento de servidor local es una configuración válida y compatible.
* No se admite el arranque SAN sobre FC-NVME.


Consulta la sección link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod Datacenter topologías"^] para conocer los requisitos de conectividad específicos de cada topología.
