---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_nexus_switching_modes_of_operation.html 
keywords: cisco, nexus, nx-os, aci, switching, modes, operation, datacenter, technical, specifications 
summary: Se pueden utilizar diversos productos Cisco Nexus como componente de conmutación en una implementación concreta de FlexPod. La mayoría de estas opciones utilizan el software Cisco NX-OS. La familia de conmutadores Cisco Nexus ofrece diversas capacidades dentro de sus líneas de productos. Estas capacidades se detallan más adelante en este documento. 
---
= Modos de funcionamiento de switches de Cisco Nexus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se pueden utilizar diversos productos Cisco Nexus como componente de conmutación en una implementación concreta de FlexPod. La mayoría de estas opciones utilizan el software Cisco NX-OS. La familia de conmutadores Cisco Nexus ofrece diversas capacidades dentro de sus líneas de productos. Estas capacidades se detallan más adelante en este documento.

La oferta de Cisco en el ámbito de las redes definidas por software se llama Application Centric Infrastructure (ACI). La línea de productos Cisco Nexus que admite el modo ACI (modo fabric) también se puede implementar en modo NX-OS.

Cisco ACI se dirige a las puestas en marcha de centros de datos que se centran en los requisitos de una aplicación específica. Las aplicaciones se crean instancias mediante una serie de perfiles y contratos que permiten la conectividad desde el host o la máquina virtual (VM) hasta el almacenamiento a través de la red.

FlexPod Datacenter está validado con ambos modos de funcionamiento de los switches Cisco Nexus. Para obtener más información sobre los modos ACI y NX-OS, consulta las siguientes páginas de Cisco:

* http://www.cisco.com/c/en/us/solutions/data-center-virtualization/application-centric-infrastructure/index.html["Infraestructura centrada en aplicaciones de Cisco"^]
* https://www.cisco.com/site/us/en/products/networking/cloud-networking/nx-os/index.html["Software Cisco NX-OS"^]

