---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_supported_versus_validated_flexpod_configurations.html 
keywords: supported, versus, validated, flexpod, datacenter, configurations, imt 
summary: 'La arquitectura de FlexPod está definida por el conjunto de reglas que se describe en este documento. Los componentes de hardware y las configuraciones de software deben ser compatibles con la lista de compatibilidad de hardware (HCL) de Cisco y con IMT de NetApp.' 
---
= Configuraciones compatibles frente a configuraciones validadas de FlexPod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
La arquitectura de FlexPod se define mediante el conjunto de normas descritas en este documento. Los componentes de hardware y las configuraciones de software deben ser compatibles con el https://ucshcltool.cloudapps.cisco.com/public["Lista de compatibilidad de hardware (HCL) de Cisco"^] y el https://imt.netapp.com["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^].

Cada diseño validado por Cisco (CVD) o arquitectura verificada por NetApp (NVA) representa una configuración validada de FlexPod. Cisco y NetApp documentan estas combinaciones de configuración y las validan mediante exhaustivas pruebas de extremo a extremo. Las implementaciones de FlexPod que se desvían de estas configuraciones cuentan con soporte completo si siguen las directrices de este documento y todos los componentes figuran como compatibles en la HCL de Cisco y en el IMT de NetApp.

Por ejemplo, la incorporación de controladores de almacenamiento o servidores Cisco UCS y la actualización del software a versiones más recientes están totalmente admitidas si el software, el hardware y las configuraciones cumplen las directrices definidas en este documento.
