---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec__netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: Los controladores de almacenamiento NetApp proporcionan la base de almacenamiento en la arquitectura FlexPod Express tanto para el almacenamiento de datos de arranque como de aplicaciones. En esta sección se enumeran las diferentes opciones de almacenamiento NetApp en la arquitectura FlexPod Express. 
---
= Componentes de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Las controladoras de almacenamiento de NetApp proporcionan la base sobre la que se basa la arquitectura FlexPod Express, tanto para el almacenamiento de datos de arranque como de aplicaciones. En esta sección se muestran las distintas opciones de NetApp de la arquitectura de FlexPod Express.



== Opciones de la controladora de almacenamiento de NetApp

Los controladores redundantes de las series AFF, ASA o FAS son necesarios en la arquitectura FlexPod Express. Los controladores ejecutan el software ONTAP. Al realizar el pedido de los controladores de almacenamiento, se puede precargar la versión de software preferida en los controladores. Para ONTAP, el clúster se puede implementar con un par de switches de interconexión de clúster o en una configuración de clúster sin switches.


NOTE: Sólo se admite una configuración de clúster sin switches para una configuración de dos nodos. Los switches de interconexión de clúster son necesarios para configuraciones con más de 4 nodos y opcionales para una configuración de dos nodos.

Existen diferentes opciones y configuraciones en función de la plataforma de almacenamiento seleccionada. Consulta a tu representante de ventas para obtener información detallada sobre estos componentes adicionales.

Las familias de controladores que se enumeran en la tabla siguiente son adecuadas para su uso en una solución FlexPod porque su conexión con los switches Cisco Nexus es perfecta. Consulta el http://hwu.netapp.com/["Hardware Universe de NetApp"^] para ver detalles específicos sobre la compatibilidad de cada modelo de controlador.

|===
| NetApp familia de almacenamiento básico para FlexPod Express | Modelo | Especificaciones técnicas 


.2+| AFF a-Series | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Documentación de AFF a-Series"] 


| A30 


| AFF C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Documentación AFF C-Series"] 


.2+| ASA A-Series | A20 .2+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentación de ASA A-Series"] 


| A30 


| ASA C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentación de ASA C-Series"] 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Documentación FAS"] 


| FAS 2820 
|===


== Bandejas de discos y discos de NetApp

Se requiere un mínimo de un estante de discos NetApp para los controladores de almacenamiento.

El tipo de bandeja de NetApp seleccionado determina los tipos de unidad disponibles en esa bandeja.


NOTE: Para obtener todos los números de pieza de disco y bandejas de discos, consulte a su representante de ventas.

Si desea más información sobre las unidades compatibles, haga clic en el enlace NetApp Hardware Universe de la siguiente tabla y, a continuación, seleccione unidades admitidas.

La siguiente tabla enumera las opciones de la bandeja de discos de NetApp, junto con las unidades compatibles con cada tipo de bandeja, que se pueden encontrar en Hardware Universe de NetApp. Siga el enlace Hardware Universe, seleccione la versión de ONTAP que utiliza y, a continuación, seleccione el tipo de bandeja. En la imagen de la bandeja, haga clic en unidades compatibles para ver las unidades compatibles con versiones específicas de ONTAP y las bandejas de discos.

|===
| Bandeja de discos | Especificaciones técnicas 


| DS212C .5+| https://hwu.netapp.com/DetailViews/Home.aspx["Unidades compatibles con bandejas de discos y medios de almacenamiento en Hardware Universe de NetApp"] 


| DS224C 


| DS460C 


| NS224 


| NS224 con NSM100B 
|===


== Opciones de licencias de software de NetApp

La siguiente tabla muestra las opciones de licencia del software NetApp.

|===
| Licencias de software de NetApp | Especificaciones técnicas 


| ONTAP One u ONTAP base para AFF y FAS .2+| Consulte a su equipo de ventas de NetApp si desea obtener más información sobre licencias. 


| ONTAP One para SAN para ASA 
|===


== Opciones de licencias de soporte de NetApp

Se requieren licencias de SupportEdge Premium y los números de pieza de dichas licencias varían en función de las opciones seleccionadas en el diseño de FlexPod Express.

La siguiente tabla enumera las opciones de licencia de soporte de NetApp para NetApp AFF, ASA y FAS Storage systems.

|===
| Licencias de soporte de NetApp | Número de pieza | Especificaciones técnicas 


| SupportEdge Premium4 horas in situ; meses: 36 | CS-O2-4HR | link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 
|===