---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_minimum_software_requirements.html 
keywords: minimum, software, requirements, flexpod, express, aff, fas, e, series 
summary: En esta sección se describen los requisitos mínimos de software para las distintas versiones de FlexPod Express. 
---
= Requisitos mínimos de software
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se describen los requisitos mínimos de software para las distintas versiones de FlexPod Express.



== Requisitos de software para FlexPod Express con NetApp AFF/ ASA/ FAS

Los requisitos de software para el FlexPod Express con NetApp AFF/ ASA/ FAS incluyen:

* ONTAP 9.16 o posterior
* Cisco NX-OS versión 10.4(6)M o posterior



NOTE: Todas las versiones de software enumeradas en esta sección son los requisitos mínimos para los componentes de hardware (NetApp y Cisco) enumerados en las secciones posteriores del documento.

Todo el software debe aparecer y ser compatible con la http://support.netapp.com/matrix/["IMT de NetApp"^]. Algunas funciones de software pueden requerir versiones de código más recientes que los mínimos indicados en arquitecturas anteriores.
