---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_technical_specifications_and_references.html 
keywords: technical, specifications, references, servers, ucs, rack, disk, shelves, aff, asa, fas, x-series-direct, c-series, adapters, controllers 
summary: En esta sección se describen otras especificaciones técnicas importantes adicionales para cada uno de los componentes de FlexPod Express. 
---
= Especificaciones técnicas y referencias
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se describen otras especificaciones técnicas importantes adicionales para cada uno de los componentes de FlexPod Express.



[[cisco-ucs-x-series-direct-chassis]]
== Chasis Direct de la serie X de Cisco UCS

Las especificaciones técnicas del chasis Direct de Cisco UCS X-Series, como se muestra en la tabla a continuación, incluyen los siguientes componentes:

* Número de unidades rack
* Número máximo de nodos
* Funcionalidad de estructura unificada
* Número de bahías de E/S para IFMS


|===
| Componente | Chasis Cisco UCS X9508 


| Unidades de rack | 7 


| Número máximo de nodos | 8 


| Con capacidad de Unified Fabric | Sí 


| Bahías de E/S para IFMS | Dos bahías para módulos de estructura inteligente (IFMS) Cisco UCS 9108 
|===
Para obtener más información, consulte link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html["Especificaciones técnicas del chasis Cisco UCS X9508 X-Series"^].



[[cisco-ucs-x-series-direct-compute-node]]
== Nodo de cómputo directo Cisco UCS X-Series

Las especificaciones técnicas para el nodo de cómputo Cisco UCS X-Series incluyen los siguientes componentes:

* Número de zócalos de procesador
* Compatibilidad con procesadores
* Capacidad de memoria
* Tamaño y velocidad
* Soporte de arranque SAN
* Número de ranuras del adaptador intermedio
* Máximo rendimiento de I/O.
* Factor de forma
* Número máximo de nodos de computación por chasis


Consulta la tabla siguiente para ver las especificaciones técnicas de los nodos de cómputo directos de Cisco UCS X-Series.

|===


| Componente | Especificaciones técnicas de Cisco UCS 


| Cisco UCS X210c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Nodo de computación Cisco UCS X210c M7"] 


| Cisco UCS X210c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Nodo de computación Cisco UCS X210c M8"] 


| Cisco UCS X215c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Nodo de computación Cisco UCS X215c M8"] 


| Cisco UCS X410c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Nodo de computación Cisco UCS X410c M7"] 


| Cisco UCS X410c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Nodo de computación Cisco UCS X410c M8"] 
|===


[[cisco-ucs-x-series-direct-fabric-interconnect]]
== Interconexión de fabric Cisco UCS X-Series Direct

Las especificaciones técnicas de Cisco UCS X-Series Direct fabric interconnect incluyen el formato, el número total de puertos y ranuras de expansión, y la capacidad de rendimiento. Consulta la tabla a continuación para ver la hoja de datos de Cisco UCS X-Series Direct fabric interconnect.

|===
| Componente | Especificaciones técnicas de Cisco UCS 


| Cisco UCS 9108 100G Fabric Interconnect | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Cisco UCS 9108 100G Fabric Interconnect"] 
|===


[[cisco-ucs-xe9305-chassis-cisco-unified-edge]]
== Chasis Cisco UCS XE9305 (Cisco Unified Edge)

Las especificaciones técnicas del chasis Cisco UCS XE9305, como se muestra en la tabla siguiente, incluyen los siguientes componentes:

|===
| Componente | Chasis Cisco UCS XE9305 


| Unidades de rack | 3 


| Número máximo de nodos | 5 nodos de cálculo Cisco UCS XE130c M8 o 2 nodos de cálculo Cisco UCS XE150c M8 
|===
Para más información, consulta la link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe9305-m8-chassis-spec-sheet.pdf["Ficha técnica del chasis Cisco UCS XE9305"^].



[[cisco-ucs-compute-nodes-for-cisco-unified-edge]]
== Nodos de cómputo Cisco UCS para Cisco Unified Edge

Las especificaciones técnicas de los nodos de cómputo Cisco UCS para Cisco Unified Edge incluyen los siguientes componentes:

* Número de zócalos de procesador
* Compatibilidad con procesadores
* Compatibilidad con GPU
* Capacidad de memoria
* Tamaño y velocidad
* Máximo rendimiento de I/O.
* Factor de forma


Los nodos de cómputo también son compatibles con GPU, el XE130c M8 es compatible con la GPU NVIDIA L4 y el XE150c M8 es compatible con las GPU NVIDIA RTX PRO 4500 / 6000 Blackwell Server Edition. Consulta la tabla a continuación para ver las especificaciones técnicas de los nodos de cómputo Cisco UCS Unified Edge.

|===


| Componente | Especificaciones técnicas de Cisco UCS 


| Nodo de computación Cisco UCS XE130c M8 | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-xe130c-m8-compute-node-spec-sheet.pdf["Nodo de computación Cisco UCS XE130c M8"] 


| Nodo de computación Cisco UCS XE150c M8 | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/unified-edge/cisco-ucs-xe150c-m8-compute-node.pdf["Nodo de computación Cisco UCS XE150c M8"] 
|===
Consulta link:https://www.cisco.com/c/en/us/products/servers-unified-computing/unified-edge/datasheet-listing.html["Listado de fichas técnicas de Cisco Unified Edge"^] para obtener más detalles.



[[cisco-ucs-c-series-rack-servers]]
== Servidores de montaje en rack Cisco UCS C-Series

Las especificaciones técnicas de los servidores en rack de la serie C de Cisco UCS incluyen la compatibilidad con procesadores, la capacidad máxima de memoria, el número de ranuras PCIe y el formato. Para obtener más detalles sobre los modelos de servidores UCS compatibles, consulta la  https://ucshcltool.cloudapps.cisco.com/public["Compatibilidad con hardware de Cisco"^] lista.

Consulta la tabla siguiente para ver las especificaciones técnicas de los servidores en rack Cisco UCS C-Series.

|===
| Componente | Especificaciones técnicas de Cisco UCS 


| Cisco UCS C220 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Servidor en rack Cisco UCS C220 M7"] 


| Cisco UCS C220 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Servidor en rack Cisco UCS C220 M8"] 


| Cisco UCS C225 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html["Servidor en rack Cisco UCS C225 M8"] 


| Cisco UCS C240 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Servidor en rack Cisco UCS C240 M7"] 


| Cisco UCS C240 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Servidor en rack Cisco UCS C240 M8"] 


| Cisco UCS C245 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Servidor en rack Cisco UCS C245 M8"] 
|===


[[cisco-nexus-switches]]
== Switches Cisco Nexus

Las especificaciones técnicas de los conmutadores Cisco Nexus figuran en la ficha técnica de cada modelo. Las especificaciones incluyen el tamaño del factor de forma, el número de supervisores, módulos de estructura y ranuras para tarjetas de línea, y el número máximo de puertos. Estas fichas técnicas se pueden consultar en la siguiente tabla.

|===
| Componente | Especificaciones técnicas de Cisco Nexus 


| Serie Nexus 9200 de Cisco | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switches Cisco Nexus serie 9200"] 


| Serie Nexus 9300 de Cisco | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Switches Cisco Nexus serie 9300"] 
|===


[[netapp-storage-controllers]]
== Controladoras de almacenamiento de NetApp

Las especificaciones técnicas de los controladores de almacenamiento NetApp incluyen la configuración de la plataforma, la capacidad bruta máxima, la memoria, el formato, los requisitos de versión de ONTAP, las bandejas de discos, etc.



[[netapp-aff-a-series]]
=== AFF A-Series de NetApp

Los controladores de almacenamiento AFF A-Series de nivel de entrada de NetApp son compatibles para su uso en FlexPod Express. Puedes encontrar información adicional en la https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Especificaciones técnicas de la serie A de AFF"^] ficha técnica y en la https://hwu.netapp.com/["Hardware Universe de NetApp"^]. Consulta la documentación específica de la plataforma que aparece en la siguiente tabla para obtener información detallada sobre un modelo AFF concreto.

|===
| Componente | Documentación de la plataforma de controladoras AFF a-Series 


| NetApp AFF A20 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a20-key-specifications.html#aff-a20-specifications-at-a-glance["Características técnicas principales del AFF A20"] 


| NetApp AFF A30 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a30-key-specifications.html#aff-a30-specifications-at-a-glance["Características técnicas principales del AFF A30"] 
|===


[[netapp-aff-c-series]]
=== NetApp AFF C-Series

Los controladores de almacenamiento AFF C-Series de nivel de entrada de NetApp son compatibles para su uso en FlexPod Express. Puedes encontrar información adicional en la https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Especificaciones técnicas de AFF C-Series"^] ficha técnica y en la https://hwu.netapp.com/["Hardware Universe de NetApp"^]. Consulta la documentación específica de la plataforma que aparece en la siguiente tabla para obtener información detallada sobre un modelo AFF concreto.

|===
| Componente | Documentación de la plataforma de controladores AFF C-Series 


| NetApp AFF C30 | https://docs.netapp.com/us-en/ontap-systems/c30-60/c30-key-specifications.html["Especificaciones clave del AFF C30"] 
|===


[[netapp-asa]]
=== NetApp ASA

Los modelos básicos de los controladores de almacenamiento ASA de NetApp son compatibles para su uso en FlexPod Express. Puedes encontrar información adicional en la https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp Especificaciones técnicas de ASA"^] ficha técnica y en la https://hwu.netapp.com/["Hardware Universe de NetApp"^]. Consulta la documentación específica de la plataforma que aparece en la siguiente tabla para obtener información detallada sobre un modelo ASA concreto.

|===
| Componente | NetApp documentación de la plataforma de controladores ASA 


| NetApp ASA A20 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a20-key-specifications.html["Especificaciones clave del ASA A20"] 


| NetApp ASA A30 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a30-key-specifications.html["Especificaciones clave del ASA A30"] 


| NetApp ASA C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Especificaciones clave del ASA C30"] 
|===


[[netapp-fas-series]]
=== Serie NetApp FAS

Las controladoras FAS de gama básica son compatibles con su uso en un FlexPod Express. Las especificaciones detalladas de todos los controladores FAS están disponibles en https://hwu.netapp.com/["Hardware Universe de NetApp"^]. Consulta la documentación específica de la plataforma que aparece en la siguiente tabla para obtener información detallada sobre un modelo FAS concreto.

|===
| Componente | Documentación de la plataforma de la controladora FAS Series 


| Serie FAS2750 | https://docs.netapp.com/us-en/ontap-systems/fas2700/overview.html["Especificaciones clave del FAS2750"^] 


| Serie FAS2820 | https://docs.netapp.com/us-en/ontap-systems/fas2800/overview.html["Especificaciones clave del FAS2820"^] 


| Serie FAS50 | https://docs.netapp.com/us-en/ontap-systems/fas50/overview.html["Especificaciones clave del FAS50"^] 
|===


[[netapp-disk-shelves]]
=== Bandejas de discos de NetApp

Las especificaciones técnicas de las bandejas de disco NetApp incluyen el tamaño del formato, el número de unidades por carcasa y los módulos de E/S de la bandeja; esta documentación se puede consultar en la siguiente tabla. Para obtener más información, consulta https://hwu.netapp.com/["Hardware Universe de NetApp"^].

|===
| Componente | Documentación de la bandeja de discos FAS/AFF de NetApp 


| Bandeja de discos DS212C de NetApp | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentación de DS212C Disk Shelf"] 


| Bandeja de discos DS224C de NetApp | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentación de la bandeja de discos DS224C"] 


| Bandeja de discos DS460C de NetApp | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentación de la bandeja de discos DS460C"] 


| Cabina de discos NetApp NS224 | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentación de la bandeja de discos NS224"] 


| NS224 con estante de discos NSM 100B | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentación de NS224 con NSM 100B Disk Shelf"] 
|===


[[netapp-drives]]
=== Unidades de NetApp

Las especificaciones técnicas de las unidades de NetApp incluyen el factor de forma de la unidad, la capacidad del disco, las revoluciones por minuto (RPM) del disco, los controladores compatibles y los requisitos de versión de ONTAP. Estas especificaciones se pueden consultar en la sección Unidades de http://hwu.netapp.com["Hardware Universe de NetApp"^].
