---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: Los controladores de almacenamiento NetApp proporcionan la base de almacenamiento en la arquitectura FlexPod Express tanto para el almacenamiento de datos de arranque como de aplicaciones. En esta sección se enumeran las diferentes opciones de almacenamiento NetApp en la arquitectura FlexPod Express. 
---
= Componentes de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Las controladoras de almacenamiento de NetApp proporcionan la base sobre la que se basa la arquitectura FlexPod Express, tanto para el almacenamiento de datos de arranque como de aplicaciones. En esta sección se muestran las distintas opciones de NetApp de la arquitectura de FlexPod Express.



[[netapp-storage-controller-options]]
== Opciones de la controladora de almacenamiento de NetApp

Los controladores redundantes de las series AFF, ASA o FAS son necesarios en la arquitectura FlexPod Express. Los controladores ejecutan el software ONTAP. Al realizar el pedido de los controladores de almacenamiento, se puede precargar la versión de software preferida en los controladores. Para ONTAP, el clúster se puede implementar con un par de switches de interconexión de clúster o en una configuración de clúster sin switches.


NOTE: La configuración de clúster sin switches solo es compatible con una configuración de dos nodos. Los switches de interconexión de clúster son obligatorios para configuraciones de cuatro o más nodos y son opcionales para una configuración de dos nodos.

Existen diferentes opciones y configuraciones en función de la plataforma de almacenamiento seleccionada. Consulta a tu representante de ventas para obtener información sobre estos componentes adicionales.

Las familias de controladores que se enumeran en la tabla siguiente son adecuadas para su uso en una solución FlexPod porque su conexión con los switches Cisco Nexus es perfecta. Consulta el http://hwu.netapp.com/["Hardware Universe de NetApp"^] para ver detalles específicos sobre la compatibilidad de cada modelo de controlador.

|===
| NetApp familia de almacenamiento básico para FlexPod Express | Modelo | Especificaciones técnicas 


.2+| AFF a-Series | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Documentación de AFF a-Series"] 


| A30 


| AFF C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Documentación de AFF C-Series"] 


.3+| ASA | A20 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentación ASA"] 


| A30 


| C30 


.3+| FAS | FAS 2750 .3+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Documentación FAS"] 


| FAS 2820 


| FAS 50 
|===


[[netapp-disk-shelves-and-disks]]
== Bandejas de discos y discos de NetApp

Se requiere como mínimo un bastidor de discos NetApp para los controladores de almacenamiento que no tienen un bastidor de discos integrado. El tipo de bastidor NetApp seleccionado determina qué tipos de unidades están disponibles en ese bastidor.


NOTE: Para obtener todos los números de pieza de disco y bandejas de discos, consulte a su representante de ventas.

La siguiente tabla muestra las opciones de bandejas de discos NetApp para FlexPod Express, junto con enlaces a sus especificaciones técnicas.

Para obtener la lista de unidades compatibles con tu shelf de discos, ve a link:https://hwu.netapp.com/DetailViews/Home.aspx["Hardware Universe de NetApp"^], en *Products > Storage > Shelves* selecciona *ONTAP (AFF, ASA, FAS)*, selecciona la versión de ONTAP que estás usando, luego selecciona el tipo de shelf (ejemplo: *DS212C*) y haz clic en *Show Results*. Haz clic en *Supported Drives* para ver las unidades compatibles con versiones específicas de ONTAP y los shelves de discos.

|===
| Bandeja de discos | Especificaciones técnicas 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["Estantes para discos y medios de almacenamiento"] 


| DS224C 


| DS460C 


| NS224 


| NS224 con NSM100B 
|===


[[netapp-software-licensing-options]]
== Opciones de licencias de software de NetApp

La siguiente tabla muestra las opciones de licencia del software NetApp.

|===
| Licencias de software de NetApp | Especificaciones técnicas 


| ONTAP One para AFF y FAS .2+| Consulte a su equipo de ventas de NetApp si desea obtener más información sobre licencias. 


| ONTAP One para SAN para ASA 
|===
Consulta este enlace para obtener más información sobre las licencias de software de NetApp: https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licencias de software de NetApp"^].



[[netapp-support-licensing-options]]
== Opciones de licencias de soporte de NetApp

Se requieren licencias de SupportEdge Premium y los números de pieza de dichas licencias varían en función de las opciones seleccionadas en el diseño de FlexPod Express.

La siguiente tabla enumera las opciones de licencia de soporte de NetApp para NetApp AFF, ASA y FAS Storage systems.

|===
| Licencias de soporte de NetApp | Especificaciones técnicas 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===