---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, asa 
summary: En esta sección se describen los requisitos de conectividad para las distintas versiones de FlexPod Express. 
---
= Requisitos de conectividad
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
En esta sección se describen los requisitos de conectividad para las distintas versiones de FlexPod Express.



== Requisitos de conectividad para FlexPod Express con NetApp AFF/ ASA/ FAS

Los requisitos de conectividad para FlexPod Express con NetApp AFF/ ASA/ FAS incluyen:

* NetApp storage controllers deben estar conectados directamente a los switches Cisco Nexus.
* Para las implantaciones UCS X-series Direct, los controladores de almacenamiento NetApp pueden conectarse directamente a los Fabric Interconnects integrados.
* No se puede colocar ningún equipo adicional entre los componentes FlexPod principales.
* Se necesitan canales de puertos virtuales (vPC) para conectar los switches Cisco Nexus 9000 series a los controladores de almacenamiento NetApp.
* Aunque no es necesario, se recomienda habilitar la compatibilidad con tramas gigantes en todo el entorno.

