---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, cabling 
summary: Esta sección describe los requisitos de alimentación y las directrices de cableado de las bandejas de discos para un diseño de FlexPod Express. 
---
= Directrices sobre alimentación eléctrica y cableado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Esta sección describe los requisitos de alimentación y las directrices de cableado para un diseño de FlexPod Express.



[[power-requirements]]
== Requisitos de alimentación

Los requisitos de alimentación para FlexPod Express varían según la ubicación donde se instale la configuración de FlexPod Express.

Para obtener más datos sobre la potencia máxima necesaria y otra información detallada sobre la alimentación, consulta la link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_technical_specifications_and_references.html["especificaciones técnicas"^] para cada componente de hardware.

Para obtener información detallada sobre el consumo energético de Cisco UCS, consulta la  https://ucspowercalculator.cisco.com/["Calculadora de potencia de Cisco UCS"^].

Para los datos de alimentación del controlador de almacenamiento NetApp, consulta el https://hwu.netapp.com["Hardware Universe de NetApp"^]. En *Plataformas*, selecciona la plataforma de almacenamiento que quieres usar (por ejemplo, AFF A20), selecciona la versión de ONTAP y luego haz clic en *Mostrar resultados*. Los datos de los cables de alimentación aparecen en la sección *Cables de alimentación compatibles* y para detalles sobre tamaño, peso, potencia, etc., consulta la sección *Tamaño, peso, acústica, potencia*.



[[cabling-guidelines]]
== Directrices de cableado

Esta sección te da pautas generales de cableado para un diseño de FlexPod Express.

* Asegúrate de que las conexiones de cómputo y almacenamiento tengan redundancia.
* La velocidad de las conexiones debe ser compatible con los componentes conectados.
* Consulta la sección link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod topologías Express"^] para obtener más directrices de cableado para topologías específicas.


La siguiente tabla ofrece directrices de cableado para las unidades de disco NetApp que pueden utilizarse en un diseño FlexPod Express.

|===


| Bandeja de discos | Directrices de cableado 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["Normas de cableado SAS"^] 


| DS224C 


| DS460C 


| NS224 .2+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Requisitos y buenas prácticas para los shelf NS224"^] 


| NS224 con NSM100B 
|===