---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_storage_software.html 
keywords: storage, software, flexpod, express, ontap, e, series, santricity 
summary: Los sistemas operativos de almacenamiento enumerados en esta sección son compatibles con la plataforma exprés de FlexPod. 
---
= Software de almacenamiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
FlexPod Express es compatible con los sistemas de almacenamiento que ejecutan los sistemas operativos NetApp ONTAP o SANtricity.



== ONTAP de NetApp

El software NetApp ONTAP es el sistema operativo que se ejecuta en los sistemas de almacenamiento AFF y FAS. ONTAP proporciona una arquitectura de almacenamiento altamente escalable que permite operaciones no disruptivas, actualizaciones no disruptivas y una infraestructura de datos ágil.

Para obtener más información acerca de ONTAP, consulte http://www.netapp.com/us/products/platform-os/ontap/index.aspx["Página de productos ONTAP"^].



== Software SANtricity de E-Series

El software SANtricity de E-Series es el sistema operativo que se ejecuta en los sistemas de almacenamiento E-Series. SANtricity proporciona un sistema muy flexible que satisface las distintas necesidades de las aplicaciones y ofrece alta disponibilidad incorporada y una amplia variedad de funciones de protección de datos.

Para más información, consulta el http://www.netapp.com/us/products/platform-os/santricity/index.aspx["Página del producto SANtricity"^].
