---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_overview.html 
keywords: flexpod, express, technical, specifications, architecture, cisco, ucs 
summary: 'FlexPod Express es una arquitectura prediseñada y basada en las mejores prácticas que se construye sobre el sistema informático unificado de Cisco (Cisco UCS) y la familia de conmutadores Cisco Nexus, y la capa de almacenamiento se construye mediante el uso de NetApp FAS o el almacenamiento E-Series de NetApp.' 
---
= TR-4293: FlexPod Express Especificaciones técnicas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthick Radhakrishnan, Arvind Ramakrishnan, Lindsey Street, Savita Kumari, NetApp

[role="lead"]
FlexPod Express es una arquitectura prediseñada con las mejores prácticas que se basa en el sistema informático unificado de Cisco (Cisco UCS) y la familia de conmutadores Nexus de Cisco, y la capa de almacenamiento se construye utilizando el NetApp FAS o el almacenamiento E-Series de NetApp. FlexPod Express es una plataforma adecuada para ejecutar varios hipervisores de virtualización y sistemas operativos (SO) bare metal y cargas de trabajo empresariales.

FlexPod Express no solo ofrece una configuración básica, sino también la flexibilidad para dimensionarse y optimizarse para adaptarse a muchos casos de uso y requisitos diferentes. Este documento clasifica las configuraciones de FlexPod Express según el sistema de almacenamiento utilizado, FlexPod Express con NetApp FAS y FlexPod Express con E-Series.
