---
sidebar: sidebar 
permalink: hybrid-cloud/cloud-fabricpool_introduction.html 
keywords: flexpod, fabricpool, inactive, data, tiering, amazon, aws, s3 
summary: Este informe técnico revisa la función de organización en niveles de datos de FabricPool de ONTAP de NetApp en el contexto de una arquitectura de infraestructura convergente FlexPod de NetApp y Cisco. 
---
= TR-4801: FlexPod con FabricPool: Organización en niveles de datos inactivos en Amazon AWS S3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Scott Kovacs, NetApp

Los precios del almacenamiento flash siguen bajando, por lo que ponen a disposición de las cargas de trabajo y aplicaciones que anteriormente no se consideraban aptas para el almacenamiento flash. No obstante, para los responsables DE TECNOLOGÍA es fundamental hacer un uso más eficiente de la inversión en almacenamiento. Los departamentos DE TECNOLOGÍA siguen presionándose para ofrecer servicios DE mayor rendimiento con un aumento mínimo o nulo del presupuesto. Para ayudarle a dar respuesta a estas necesidades, FabricPool de NetApp le permite aprovechar la rentabilidad del cloud al mover los datos que se usan con poca frecuencia del costoso almacenamiento flash en las instalaciones a un nivel de almacenamiento más rentable en el cloud público. Mover datos a los que se accede con poca frecuencia al cloud libera espacio de almacenamiento flash muy valioso en sistemas AFF o FAS para ofrecer más capacidad para las cargas de trabajo críticas para el negocio en el nivel flash de alto rendimiento.

En este informe técnico se revisa la función de organización en niveles de datos de FabricPool de ONTAP de NetApp en el contexto de una arquitectura de infraestructura convergente FlexPod de NetApp y Cisco. Debe estar familiarizado con la arquitectura de la infraestructura convergente del centro de datos de FlexPod y el software de almacenamiento de ONTAP para aprovechar completamente los conceptos descritos en este informe técnico. Partiendo de la familiaridad con FlexPod y ONTAP, hablamos de FabricPool, de cómo funciona y de cómo puede utilizarse para lograr un uso más eficiente del almacenamiento flash en las instalaciones. Gran parte del contenido de este informe se trata con mayor detalle en https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598 mejores prácticas de FabricPool"^] Y otra documentación de producto de ONTAP. El contenido se ha condensado en una infraestructura de FlexPod y no cubre por completo todos los casos de uso de FabricPool. Todas las características y conceptos examinados están disponibles en ONTAP 9.6.

Puede encontrar información adicional sobre FlexPod en https://www.netapp.com/pdf.html?item=/media/12424-tr4036.pdf["TR-4036 Especificaciones técnicas de FlexPod Datacenter"^].
