---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-installation-and-configuration.html 
keywords: cloud volumes ontap, flexpod, ontap netapp console, installation, configuration 
summary: Esta sección describe cómo instalar y configurar Cloud Volumes ONTAP, FlexPod, el almacenamiento ONTAP y la NetApp Console. 
---
= Instalación y configuración
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-solution-components.html["Anterior: Componentes de la solución."]



== Cloud Volumes ONTAP de NetApp

Complete los pasos siguientes para configurar la instancia de Cloud Volumes ONTAP:

. Preparar el entorno de proveedor de servicios de cloud público.
+
Debe capturar los detalles del entorno de su proveedor de servicios de cloud público para la configuración de la solución. Por ejemplo, para la preparación del entorno de Amazon Web Services (AWS), necesita la clave de acceso de AWS, la clave secreta de AWS y otros detalles de red como región, VPC, subred, etc.

. Configure la puerta de enlace del extremo VPC.
+
Se requiere una puerta de enlace de extremo de VPC para habilitar la conexión entre el VPC y el servicio de AWS S3. Se utiliza para habilitar la copia de seguridad en CVO, un extremo con el tipo de puerta de enlace.

. Acceda a la NetApp Console.
+
Para acceder a la consola y otros servicios en la nube, debe registrarse en https://cloudmanager.netapp.com/["NetApp Console"^] .  Para configurar espacios de trabajo y usuarios en la cuenta de la consola, consulte https://docs.netapp.com/us-en/console-setup-admin/index.html["Configuración y administración de la NetApp Console"^] .  Necesitas una cuenta que tenga permiso para implementar el agente de la consola en tu proveedor de nube directamente desde la consola.  Para obtener los permisos que necesita, consulte https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-permissions.html["Resumen de permisos para la NetApp Console"^] .

. Implementar agente de consola.
+
Antes de agregar un sistema Cloud Volume ONTAP , debe implementar un agente de consola.  La consola le avisará si intenta crear su primer sistema Cloud Volumes ONTAP sin un agente de consola instalado.  Para implementar un agente de consola en AWS desde la consola, consulte la https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-aws.html["Opciones de instalación del agente de consola en AWS"^] .

. Inicie Cloud Volumes ONTAP en AWS.
+
Puede iniciar Cloud Volumes ONTAP en una configuración con un único sistema o como par de alta disponibilidad en AWS. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-aws.html["Lea las instrucciones paso a paso"^].

+
Para obtener información detallada sobre estos pasos, consulte https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["Guía de inicio rápido para Cloud Volumes ONTAP en AWS"^].

+
En esta solución, hemos implementado un sistema Cloud Volumes ONTAP de un solo nodo en AWS.





== Puesta en marcha de FlexPod en las instalaciones

Para comprender los detalles sobre el diseño de FlexPod con UCS X-Series, VMware y ONTAP de NetApp, consulte https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["Centro de datos FlexPod con Cisco UCS X-Series"^] guía de diseño. Este documento proporciona directrices de diseño para incorporar la plataforma Cisco Intersight-Series gestionada UCS X-Series en la infraestructura de centro de datos FlexPod.

Para implementar la instancia de FlexPod en las instalaciones, consulte https://netapp-https:/www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.htmlmy.sharepoint.com/personal/dorianh_netapp_com/Documents/Projects/Github%20Conversions/FlexPod/TR-4960/TR-4960%20FlexPod%20hybrid%20cloud%20with%20CVO%20for%20Epic%20latest-Feb14.docx["esta guía de implementación"^].

Este documento proporciona directrices de puesta en marcha para incorporar la plataforma Cisco Intersight-Series gestionada por UCS X-Series en una infraestructura de centro de datos FlexPod. El documento abarca tanto las configuraciones como las mejores prácticas para una correcta puesta en marcha.

FlexPod se puede implementar tanto en UCS Managed Mode como en Cisco Intersight Managed Mode (IMM). Si va a implementar FlexPod en UCS Managed Mode, consulte este tema https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["guía de diseño"^] y esto https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["guía de puesta en marcha"^].

La puesta en marcha de FlexPod se puede automatizar con Infraestructura como código con Ansible. A continuación puede ver los enlaces a los repositorios de GitHub para una puesta en marcha completa de FlexPod:

* Podemos ver la configuración de Ansible de FlexPod con Cisco UCS en el modo gestionado de UCS, ONTAP de NetApp y VMware vSphere https://github.com/ucs-compute-solutions/FlexPod-UCSM-M6["aquí"^].
* Podrá ver la configuración de Ansible de FlexPod con Cisco UCS en IMM, ONTAP de NetApp y VMware vSphere https://github.com/ucs-compute-solutions/FlexPod-IMM-4.2.2["aquí"^].




== Configuración del almacenamiento ONTAP en las instalaciones

En esta sección se describen algunos de los pasos importantes para la configuración de ONTAP específicos de esta solución.

. Configure una SVM con el servicio iSCSI en ejecución.
+
....
1. vserver create -vserver Healthcare_SVM -rootvolume Healthcare_SVM_root -aggregate aggr1_A400_G0312_01 -rootvolume-security-style unix
2. vserver add-protocols -vserver Healthcare_SVM -protocols iscsi
3. vserver iscsi create -vserver Healthcare_SVM

   To verify:

   A400-G0312::> vserver iscsi show -vserver Healthcare_SVM
   Vserver: Healthcare_SVM
   Target Name:
   iqn.1992-08.com.netapp:sn.1fbf00f438c111ed866cd039ea91fb56:vs.3
   Target Alias: Healthcare_SVM
   Administrative Status: up
....
+
Si no se instaló la licencia iSCSI durante la configuración del clúster, asegúrese de instalar la licencia antes de crear el servicio iSCSI.

. Cree un volumen de FlexVol.
+
....
1. volume create -vserver Healthcare_SVM -volume hc_iscsi_vol -aggregate aggr1_A400_G0312_01 -size 500GB -state online -policy default -space guarantee none
....
. Añada interfaces para el acceso iSCSI.
+
....
1. network interface create -vserver Healthcare_SVM -lif iscsi-lif-01a -service-policy default-data-iscsi -home-node <st-node01> -home-port a0a-<infra-iscsi-a-vlan-id> -address <st-node01-infra-iscsi-a-ip> -netmask <infra-iscsi-a-mask> -status-admin up
2. network interface create -vserver Healthcare_SVM -lif iscsi-lif-01b -service-policy default-data-iscsi -home-node <st-node01> -home-port a0a-<infra-iscsi-b-vlan-id> -address <st-node01-infra-iscsi-b-ip> -netmask <infra-iscsi-b-mask> -status-admin up
3. network interface create -vserver Healthcare_SVM -lif iscsi-lif-02a -service-policy default-data-iscsi -home-node <st-node02> -home-port a0a-<infra-iscsi-a-vlan-id> -address <st-node02-infra-iscsi-a-ip> -netmask <infra-iscsi-a-mask> -status-admin up
4. network interface create -vserver Healthcare_SVM -lif iscsi-lif-02b -service-policy default-data-iscsi -home-node <st-node02> -home-port a0a-<infra-iscsi-b-vlan-id> -address <st-node02-infra-iscsi-b-ip> -netmask <infra-iscsi-b-mask> -status-admin up
....
+
En esta solución, creamos cuatro interfaces lógicas iSCSI (LIF), dos en cada nodo.

+
Una vez que la instancia de FlexPod está en funcionamiento con vCenter implementada y todos los hosts ESXi añadidos, debemos poner en marcha una máquina virtual Linux que actúa como un servidor que se conecta y accede al almacenamiento ONTAP de NetApp. En esta solución, hemos instalado una instancia de CentOS 8 en vCenter.

. Cree una LUN.
+
....
1. lun create -vserver Healthcare_SVM -path /vol/hc_iscsi_vol/iscsi_lun1 -size 200GB -ostype linux -space-reserve disabled
....
+
En el caso de una base de datos operativa EHR (ODB), un diario y cargas de trabajo de aplicaciones, EHR recomienda presentar almacenamiento a los servidores como LUN iSCSI. NetApp también admite el uso de FCP y NVMe/FC si tiene versiones de AIX y los sistemas operativos RHEL que sean compatibles, lo que mejora el rendimiento. FCP y NVMe/FC pueden coexistir en la misma estructura.

. Cree un igroup.
+
....
1. igroup create -vserver Healthcare_SVM -igroup ehr -protocol iscsi -ostype linux -initiator iqn.1994-05.com.redhat:8e91e9769336
....
+
Los iGroups se utilizan para permitir el acceso del servidor a las LUN. Para el host Linux, el IQN del servidor se puede encontrar en el archivo `/etc/iscsi/initiatorname.iscsi`.

. Asigne la LUN al igroup.
+
....
1. lun mapping create -vserver Healthcare_SVM -path /vol/hc_iscsi_vol/iscsi_lun1 -igroup ehr -lun-id 0
....




== Agregue almacenamiento FlexPod local a la NetApp Console

Complete los siguientes pasos para agregar su almacenamiento FlexPod al sistema mediante la consola.

. Desde el menú de navegación, seleccione *Almacenamiento* > *Sistemas*.
. En la página Sistemas, haga clic en *Agregar sistema* y seleccione *Local*.
. Seleccione *On-local ONTAP*. Haga clic en *Siguiente*.
. En la página ONTAP Cluster Details, introduzca la dirección IP de administración del clúster y la contraseña de la cuenta de usuario de administrador. A continuación, haga clic en *Agregar*.
. En la página Detalles y credenciales, introduzca un nombre y una descripción para el entorno de trabajo y, a continuación, haga clic en *Ir*.
+
La consola detecta el clúster ONTAP y lo agrega como sistema en la página Sistemas.



Si quiere más información, consulte la página https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html["Detectar clústeres de ONTAP en las instalaciones"^].

link:fhc-cvoe-san-configuration.html["Siguiente: Configuración DE SAN."]
