---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-conclusion.html 
keywords: conclusion 
summary: Crear un cloud híbrido es un objetivo para la mayoría de las organizaciones sanitarias de proporcionar disponibilidad de datos en cualquier momento. En esta solución, implementamos una solución de cloud híbrido FlexPod con Cloud Volumes ONTAP y utilizamos la tecnología de replicación SnapMirror de NetApp para validar algunos casos prácticos con el fin de realizar backups y recuperar aplicaciones y cargas de trabajo de atención médica. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-solution-validation.html["Anterior: Validación de la solución."]

[role="lead"]
Crear un cloud híbrido es un objetivo para la mayoría de las organizaciones sanitarias de proporcionar disponibilidad de datos en cualquier momento. En esta solución, implementamos una solución de cloud híbrido FlexPod con Cloud Volumes ONTAP y utilizamos la tecnología de replicación SnapMirror de NetApp para validar algunos casos prácticos con el fin de realizar backups y recuperar aplicaciones y cargas de trabajo de atención médica.

FlexPod, una infraestructura convergente rigurosamente probada y validada previamente de la alianza estratégica de Cisco y NetApp, ha sido diseñada para proporcionar un rendimiento de sistema de baja latencia predecible y una alta disponibilidad. Este enfoque da como resultado altos niveles de confort de EHR y, en última instancia, el mejor tiempo de respuesta para los usuarios del sistema EHR.

Con NetApp, podrá ejecutar la producción de EHR, la recuperación ante desastres, el backup o la organización en niveles en el cloud tal como lo haría con las funciones de almacenamiento de NetApp en un centro de datos en las instalaciones. Con Cloud Volumes ONTAP de NetApp, NetApp proporciona las funcionalidades de clase empresarial y el rendimiento necesario para ejecutar EHR en el cloud de forma efectiva. Las opciones de cloud de NetApp proporcionan iSCSI de bloque a bloque y SMB o NFS.

Esta solución satisface la necesidad de las organizaciones sanitarias y permite dar un paso adelante hacia su transformación digital. También puede ayudarles a gestionar sus aplicaciones y cargas de trabajo de forma eficiente.

link:fhc-cvoe-where-to-find-additional-information.html["Siguiente: Dónde encontrar información adicional."]
