---
sidebar: sidebar 
permalink: hybrid-cloud/flexpod-rho-cvo-solution-validation_overview.html 
keywords: validation, overview, restoring, application mobility, 
summary: En esta sección, revisamos la solución con varios casos de uso validados. 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-rho-cvo-astra-control-center-installation-on-openshift-container-platform.html["Anterior: Instalación de Astra Control Center en OpenShift Container Platform."]

En esta sección, vamos a revisar la solución con algunos casos de uso:

* Restaurar una aplicación con estado desde una copia de seguridad remota a otro clúster de OpenShift que se ejecuta en la nube.
* Restaurar una aplicación con estado en el mismo espacio de nombres en el clúster de OpenShift.
* Movilidad de aplicaciones mediante la clonación de un sistema FlexPod (OpenShift Container Platform Bare Metal) a otro sistema FlexPod (OpenShift Container Platform en VMware).


Cabe destacar que en esta solución sólo se validan algunos casos de uso. Esta validación no representa en modo alguno toda la funcionalidad de Astra Control Center.

link:flexpod-rho-cvo-application-recovery-with-remote-backups.html["Siguiente: Recuperación de aplicaciones con backups remotos."]
