---
sidebar: sidebar 
permalink: vdi/fpd-vmw-horiz-ontap.html 
keywords: flexpod, cisco, aff, vmware, horizon, vsphere, ucs, ontap, a300, design 
summary: Este documento constituye una guía de diseño y arquitectura de referencia para un entorno informático de usuario final de 5000 puestos a 6000 puestos en el centro de datos FlexPod con Cisco UCS y AFF A300 de NetApp, así como el software de gestión de datos ONTAP de NetApp. 
---
= FlexPod Datacenter con VMware Horizon View 7,10, VMware vSphere 6,7 U2, Cisco UCS Manager 4,0 y NetApp ONTAP 9,6 para un máximo de 6700 puestos
:allow-uri-read: 


Vadim Lebedev, Cisco Suresh Thoppay, NetApp

Este documento constituye una guía de diseño y arquitectura de referencia para un entorno informático de usuario final de 5000 puestos a 6000 puestos en el centro de datos FlexPod con Cisco UCS y AFF A300 de NetApp, así como el software de gestión de datos ONTAP de NetApp. La solución incluye sesiones RDS basadas en servidor de VMware Horizon Windows Server 2019, puestos de trabajo virtuales persistentes y con clonado completo de Microsoft Windows 10, y puestos de trabajo virtuales de Microsoft Windows 10 con clonado instantáneo y sin persistencia de VMware Horizon en VMware vSphere 6,7 U2.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_ontap96_vmware710_67_u2_ucs_40_6700_seats.html["FlexPod Datacenter con VMware Horizon View 7,10, VMware vSphere 6,7 U2, Cisco UCS Manager 4,0 y NetApp ONTAP 9,6 para un máximo de 6700 puestos"^]
