---
sidebar: sidebar 
permalink: flexpod-dc/fpd-cisco-vsphere.html 
keywords: flexpod, cisco, data, center, ontap, ucs, xeon, vmware, vsphere, aff 
summary: 'Este documento describe Cisco y NetApp FlexPod Datacenter con NetApp ONTAP 9,6, el software unificado Cisco UCS Manager versión 4,0(4) con procesadores escalables Intel Xeon de segunda generación y VMware vSphere 6,7 U2.' 
---
= FlexPod Datacenter con VMware vSphere 6,7 U2, Cisco UCS fouth-generation Fabric y NetApp ONTAP 9,6
:allow-uri-read: 


John George, Cisco Sree Lakshmi Lanka, NetApp

[role="lead"]
Este documento describe Cisco y NetApp FlexPod Datacenter con NetApp ONTAP 9,6, el software unificado Cisco UCS Manager versión 4,0(4) con procesadores escalables Intel Xeon de segunda generación y VMware vSphere 6,7 U2. Cisco UCS Manager (UCSM) 4,0(4) proporciona un soporte consolidado para:

* Todos los modelos actuales de interconexión de estructura de Cisco UCS: 6200, 6300, 6324 (Cisco UCS Mini)
* 6454
* IOM de la serie 2200/2300/2400
* Cisco UCS serie B
* Cisco UCS C-Series.


FlexPod Datacenter con NetApp ONTAP 9,6, el software unificado Cisco UCS versión 4,0 (4), y VMware vSphere 6,7 U2 es una arquitectura de centro de datos prediseñada y mejor práctica integrada en el sistema Cisco Unified Computing System (Cisco UCS), la familia de switches Cisco Nexus 9000, switches estructurales multicapa MDS 9000, Y las cabinas de almacenamiento AFF A-Series de NetApp que ejecutan ONTAP 9.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_vmware_netappaffa_u2.html["FlexPod Datacenter con VMware vSphere 6,7 U2, Cisco UCS de cuarta generación Fabric y NetApp ONTAP 9,6"^]
