---
sidebar: sidebar 
permalink: flexpod-dc/fpd-mcc-vsphere-deploy.html 
keywords: flexpod, cisco, data, center, aci, multi-pod, mcc, ip, vmware, vsphere, deployment 
summary: Cisco y NetApp se han asociado para ofrecer una serie de soluciones FlexPod que permiten crear plataformas estratégicas de centros de datos. 
---
= FlexPod Datacenter con Cisco ACI Multi-Pod con NetApp MetroCluster IP y VMware vSphere 6,7: Puesta en marcha
:allow-uri-read: 


Haseeb Niazi, Cisco Ramesh Issac y Cisco Arvind Ramakrishnan y NetApp

Cisco y NetApp se han asociado para ofrecer una serie de soluciones FlexPod que permiten crear plataformas estratégicas de centros de datos. La solución FlexPod proporciona una arquitectura integrada que incorpora prácticas de diseño recomendadas para informática, almacenamiento y redes, lo que minimiza los riesgos TECNOLÓGICOS gracias a la validación de la arquitectura integrada para garantizar la compatibilidad entre varios componentes. La solución también soluciona los problemas DE TI al proporcionar indicaciones de diseño documentadas, directrices para la puesta en marcha y soporte que se puede utilizar en varias etapas (planificación, diseño e implementación) de una implementación.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi67_n9k_aci_metrocluster.html["FlexPod Datacenter con Cisco ACI Multi-Pod con NetApp MetroCluster IP y VMware vSphere 6,7: Puesta en marcha"^]
