---
sidebar: sidebar 
permalink: flexpod-dc/fpd-cisco-vsphere-deploy.html 
keywords: flexpod, cisco, data, center, vmware, vsphere, ucs, ontap 
summary: 'Este documento describe Cisco y NetApp FlexPod Datacenter con el software unificado Cisco UCS Manager, versión 4,0 (2) y VMware vSphere 6,7 U1.' 
---
= FlexPod Datacenter con VMware vSphere 6,7 U1, la estructura de cuarta generación de Cisco UCS y AFF A-Series de NetApp
:allow-uri-read: 


John George, Cisco Scott Kovacs, NetApp

[role="lead"]
Este documento describe Cisco y NetApp FlexPod Datacenter con el software unificado Cisco UCS Manager, versión 4,0 (2) y VMware vSphere 6,7 U1. Cisco UCS Manager (UCSM) 4,0(2) proporciona soporte consolidado de todos los modelos actuales de interconexión de estructura de Cisco UCS (6200, 6300, 6324 (Cisco UCS Mini)), IOM de la serie 6454,2200/2300, Cisco UCS B-Series y Cisco UCS C-Series. FlexPod Datacenter con Cisco UCS Unified Software release 4,0(2) y VMware vSphere 6,7 U1 es una arquitectura de centro de datos prediseñada con las mejores prácticas basada en Cisco Unified Computing System (UCS), la familia de switches Cisco Nexus 9000, switches estructurales MDS 9000 multicapa, Asimismo, las cabinas de almacenamiento AFF A-Series de NetApp que ejecutan el sistema operativo de almacenamiento 9 de ONTAP.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_vmware_netappaffa.html["FlexPod Datacenter con VMware vSphere 6,7 U1, la estructura de cuarta generación de Cisco UCS y AFF A-Series de NetApp"^]
