---
sidebar: sidebar 
permalink: flexpod-dc/fpd-vsphere-deploy.html 
keywords: cisco, flexpod, data, center, vmware, vsphere, ontap, deployment 
summary: 'Este documento describe FlexPod Datacenter de Cisco y NetApp con ONTAP 9,7 de NetApp en el sistema de almacenamiento all-flash AFF A400 de NetApp, el software unificado Cisco UCS Manager versión 4,1(2) con procesadores escalables Intel Xeon Scalable de segunda generación y VMware vSphere 7,0.' 
---
= FlexPod Datacenter con VMware vSphere 7,0 y NetApp ONTAP 9,7: Puesta en marcha
:allow-uri-read: 


John George, Cisco Sree Lakshmi Lanka, NetApp

Este documento describe FlexPod Datacenter de Cisco y NetApp con ONTAP 9,7 de NetApp en el sistema de almacenamiento all-flash AFF A400 de NetApp, el software unificado Cisco UCS Manager versión 4,1(2) con procesadores escalables Intel Xeon Scalable de segunda generación y VMware vSphere 7,0. Cisco UCS Manager (UCSM) 4,1(2) proporciona un soporte consolidado para:

* Todos los modelos actuales de interconexión de estructura de Cisco UCS: 6200, 6300, 6324 (Cisco UCS Mini)
* 6400
* IOM de la serie 2200/2300/2400
* Cisco UCS serie B
* Cisco UCS C-Series


También se incluyen las plataformas de gestión de SaaS Cisco Intersight y NetApp Active IQ.

FlexPod Datacenter con NetApp ONTAP 9,7, el software unificado Cisco UCS versión 4,1 (2) y VMware vSphere 7,0 constan de una arquitectura de centro de datos prediseñada y con mejores prácticas integrada en Cisco Unified Computing System (Cisco UCS), la familia de switches Cisco Nexus 9000, switches estructurales MDS 9000 multicapa, Y las cabinas de almacenamiento AFF A-Series de NetApp que ejecutan el software de gestión de datos ONTAP 9,7.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/fp_vmware_vsphere_7_0_ontap_9_7.html["FlexPod Datacenter con VMware vSphere 7,0 y NetApp ONTAP 9,7: Puesta en marcha"^]
