---
sidebar: sidebar 
permalink: flexpod-dc/sm-bcs-where-to-find-additional-information-and-version-history.html 
keywords:  
summary:  
---
= Dónde encontrar información adicional e historial de versiones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:sm-bcs-conclusion.html["Anterior: Conclusión."]

[role="lead"]
Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:



== FlexPod

* Página de inicio de FlexPod
+
https://www.flexpod.com["https://www.flexpod.com"^]

* Guías de puesta en marcha y diseño validado por Cisco para FlexPod
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* Servidores Cisco - sistema de computación unificada (UCS)
+
https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html["https://www.cisco.com/c/en/us/products/servers-unified-computing/index.html"^]

* Documentación de productos de NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Guía de diseño de FlexPod Datacenter con Cisco UCS 4.2(1) en UCS Managed Mode, VMware vSphere 7.0 U2 y NetApp ONTAP 9.9
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html"^]

* Guía de puesta en marcha de FlexPod Datacenter con Cisco UCS 4.2(1) en UCS Managed Mode, VMware vSphere 7.0 U2 y NetApp ONTAP 9.9
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2.html"^]

* Guía de diseño de FlexPod Datacenter con Cisco UCS X-Series, VMware 7.0 U2 y NetApp ONTAP 9.9
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html"^]

* Guía de puesta en marcha de FlexPod Datacenter con Cisco UCS X-Series, VMware 7.0 U2 y NetApp ONTAP 9.9
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.html"^]

* Guía de diseño de FlexPod Express para VMware vSphere 7.0 con Cisco UCS Mini y AFF/FAS NVA de NetApp
+
https://www.netapp.com/pdf.html?item=/media/22621-nva-1154-DESIGN.pdf[]

* Guía de puesta en marcha de FlexPod Express para VMware vSphere 7.0 con Cisco UCS Mini y AFF/FAS NVA de NetApp
+
https://www.netapp.com/pdf.html?item=/media/21938-nva-1154-DEPLOY.pdf[]

* FlexPod MetroCluster IP con estructura de interfaz multisitio VXLAN
+
https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/flexpod-metrocluster-ip-vxlan-multi-site-wp.pdf["https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/flexpod-metrocluster-ip-vxlan-multi-site-wp.pdf"^]

* NAbox
+
https://nabox.org["https://nabox.org"^]

* Cosecha de NetApp
+
https://github.com/NetApp/harvest/releases["https://github.com/NetApp/harvest/releases"^]





== SM-BC

* SM-BC
+
https://docs.netapp.com/us-en/ontap/smbc/index.html["https://docs.netapp.com/us-en/ontap/smbc/index.html"^]

* TR-4878: Continuidad del negocio de SnapMirror (SM-BC) ONTAP 9.8
+
https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf["https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf"^]

* Cómo eliminar correctamente una relación de SnapMirror con ONTAP 9
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_correctly_delete_a_SnapMirror_relationship_ONTAP_9["https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_correctly_delete_a_SnapMirror_relationship_ONTAP_9"^]

* Conceptos básicos de la recuperación ante desastres de SnapMirror Synchronous
+
https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html["https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html"^]

* Conceptos básicos de la recuperación ante desastres de SnapMirror asíncrono
+
https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html#data-protection-relationships"^]

* Protección de datos y recuperación ante desastres
+
https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html"^]

* Instale o actualice el servicio Mediator de ONTAP
+
https://docs.netapp.com/us-en/ontap/mediator/index.html["https://docs.netapp.com/us-en/ontap/mediator/index.html"^]





== VMware vSphere ha y vSphere Metro Storage Cluster

* Crear y usar clústeres de vSphere ha
+
https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.avail.doc/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html["https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.avail.doc/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html"^]

* VMware vSphere Metro Storage Cluster (VMSC)
+
https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc"^]

* Prácticas recomendadas para VMware vSphere Metro Storage Cluster
+
https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-recommended-practices["https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-recommended-practices"^]

* ONTAP de NetApp con la continuidad empresarial de SnapMirror de NetApp (SM-BC) con VMware vSphere Metro Storage Cluster (VMSC). (83370)
+
https://kb.vmware.com/s/article/83370["https://kb.vmware.com/s/article/83370"^]

* Proteja aplicaciones y bases de datos de nivel 1 con el clúster de almacenamiento Metro de VMware vSphere y ONTAP
+
https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-tier-1-applications-and-databases-with-VMware-vSphere-Metro-Storage/ba-p/171636["https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-tier-1-applications-and-databases-with-VMware-vSphere-Metro-Storage/ba-p/171636"^]





== Microsoft SQL y HammerDB

* Microsoft SQL Server 2019
+
https://www.microsoft.com/en-us/sql-server/sql-server-2019["https://www.microsoft.com/en-us/sql-server/sql-server-2019"^]

* Guía de prácticas recomendadas de desarrollo de arquitectura de Microsoft SQL Server en VMware vSphere
+
https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/solutions/sql-server-on-vmware-best-practices-guide.pdf["https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/solutions/sql-server-on-vmware-best-practices-guide.pdf"^]

* Sitio web de HammerDB
+
https://www.hammerdb.com["https://www.hammerdb.com"^]





== Matriz de compatibilidad

* Matriz de compatibilidad de hardware de Cisco UCS
+
https://ucshcltool.cloudapps.cisco.com/public/["https://ucshcltool.cloudapps.cisco.com/public/"^]

* Herramienta de matriz de interoperabilidad de NetApp
+
https://support.netapp.com/matrix/["https://support.netapp.com/matrix/"^]

* Hardware Universe de NetApp
+
https://hwu.netapp.com["https://hwu.netapp.com"^]

* Guía de compatibilidad de VMware
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Abril de 2022 | Versión inicial. 
|===