---
sidebar: sidebar 
permalink: healthcare/medical-imaging_conclusion.html 
keywords: medical, imaging, flexpod, healthcare, organization, productivity, conclusion 
summary: Al ejecutar un entorno de imágenes médicas en FlexPod, su organización de atención médica puede esperar una mejora en la productividad del personal y una reducción en los gastos de capital y operativos. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Al ejecutar un entorno de imágenes médicas en FlexPod, su organización de atención médica puede esperar una mejora en la productividad del personal y una reducción en los gastos de capital y operativos. FlexPod proporciona una infraestructura convergente prevalidada y rigurosamente probada desde la alianza estratégica de Cisco y NetApp. Se ha diseñado y diseñado específicamente para proporcionar un sistema predecible de baja latencia y una alta disponibilidad. Este enfoque resulta en una experiencia de usuario superior y un tiempo de respuesta óptimo para los usuarios del sistema de imágenes médicas.

Los diferentes componentes de un sistema de imágenes médicas requieren almacenamiento de datos en sistemas de archivos SMB/CIFS, NFS, Ext4 y NTFS. Por lo tanto, su infraestructura debe proporcionar acceso a datos mediante protocolos NFS, SMB/CIFS y SAN. Los sistemas de almacenamiento de NetApp admiten estos protocolos desde una única cabina de almacenamiento.

Alta disponibilidad, eficiencia del almacenamiento, backups rápidos y programados basados en copias Snapshot, operaciones de restauración rápidas, replicación de datos para recuperación ante desastres y las funcionalidades de infraestructura de almacenamiento de FlexPod proporcionan un sistema de almacenamiento y gestión de datos líder en el sector.
