---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-rac-db.html 
keywords: flexpod, datacenter, oracle, rac, cisco, ucs, aff, mds, deploy 
summary: Los diseños validados por Cisco incluyen sistemas y soluciones diseñados, probados y documentados para facilitar y mejorar las puestas en marcha de los clientes. 
---
= Centro de datos FlexPod con bases de datos RAC de Oracle en Cisco UCS y AFF A-Series de NetApp
:allow-uri-read: 


Tushar Patel, Cisco Hardikkumar Vyas, Cisco

[role="lead"]
Los diseños validados por Cisco incluyen sistemas y soluciones diseñados, probados y documentados para facilitar y mejorar las puestas en marcha de los clientes. Estos diseños incorporan una amplia gama de tecnologías y productos en una cartera de soluciones que se han desarrollado para satisfacer las necesidades empresariales de los clientes. Cisco y NetApp se han asociado para ofrecer FlexPod, que sirve como base para una variedad de cargas de trabajo y permite diseñar arquitecturas eficientes que se basan en los requisitos del cliente. Una solución FlexPod es un enfoque validado para poner en marcha tecnologías de Cisco y NetApp como infraestructura de nube compartida.

El centro de datos FlexPod con el sistema AFF all-flash de NetApp es una plataforma de infraestructura convergente que combina las mejores tecnologías de Cisco y NetApp en una potente plataforma convergente para aplicaciones empresariales. Cisco y NetApp trabajan estrechamente con Oracle para dar cabida a las bases de datos más exigentes en cuanto a tiempos de respuesta y transacciones que requieren las empresas actuales.

Este diseño validado por Cisco (CVD) describe la arquitectura FlexPod Datacenter de referencia usando Cisco UCS y All Flash AFF Storage de NetApp para implementar un entorno de base de datos Oracle RAC de alta disponibilidad. Este documento muestra la configuración de hardware y software de los componentes involucrados y los resultados de varias pruebas. Además, este documento ofrece directrices de implementación y prácticas recomendadas con servidores de computación Cisco UCS, switches de interconexión de estructura Cisco, switches Cisco MDS, switches Cisco Nexus, almacenamiento AFF de NetApp y base de datos Oracle RAC.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["Centro de datos FlexPod con bases de datos RAC de Oracle en Cisco UCS y AFF A-Series de NetApp"^]
