---
sidebar: sidebar 
permalink: ent-db/fpd-sap-sql-deploy.html 
keywords: flexpod, cisco, sap, sql, servers, data, bases 
summary: FlexPod es una solución de centro de datos prevalidada y diseñada para responder a los rápidos cambios en las necesidades de los departamentos DE TECNOLOGÍA. 
---
= Pon en marcha servidores de aplicaciones SAP en FlexPod con SQL
:allow-uri-read: 


FlexPod es una solución de centro de datos prevalidada y diseñada para responder a los rápidos cambios en las necesidades de los departamentos DE TECNOLOGÍA. Cisco y NetApp se han asociado para proporcionar FlexPod, que utiliza los mejores componentes informáticos, de redes y almacenamiento como base para diversas cargas de trabajo empresariales, como bases de datos, planificación de recursos empresariales (ERP), gestión de relaciones con los clientes (CRM) y aplicaciones web. La consolidación de las aplicaciones DE TI, en particular las bases de datos, ha generado un interés considerable en los últimos años. La plataforma de bases de datos más adoptada e instalada en los últimos años es Microsoft SQL Server. Las bases de datos de SQL Server con frecuencia se han convertido en sujetos al aumento descontrolado de las bases de datos, lo cual lleva a retos de TI, como servidores infrautilizados, licencias incorrectas, problemas de seguridad, preocupaciones de gestión y enormes costes operativos. Por lo tanto, las bases de datos de SQL Server son buenas candidatas para la consolidación en una plataforma más sólida, flexible y resiliente. Este documento describe la arquitectura de referencia de FlexPod para desplegar y consolidar bases de datos SQL Server.

link:https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/sap-appservers-flexpod-with-sql.pdf["Pon en marcha servidores de aplicaciones SAP en FlexPod con SQL"^]
