---
sidebar: sidebar 
permalink: ent-db/fpd-sap-ucs-aff.html 
keywords: flexpod, cisco, data, center, sap, ucs, aff, a-series, tdi, tailored, design 
summary: 'Este documento describe la solución FlexPod de Cisco y NetApp, la cual es un enfoque validado para la puesta en marcha de entornos de integración personalizada del centro de datos (TDI) de SAP HANA.' 
---
= FlexPod Datacenter para la solución SAP con Cisco UCS Manager 4,0 y NetApp AFF A–Series: Diseño
:allow-uri-read: 


Pramod Ramamurthy, Cisco Marco Schoen, NetApp

[role="lead"]
Este documento describe la solución FlexPod de Cisco y NetApp, la cual es un enfoque validado para la puesta en marcha de entornos de integración personalizada del centro de datos (TDI) de SAP HANA. Este diseño validado proporciona directrices y un marco para implementar SAP HANA con prácticas recomendadas de Cisco y NetApp.

FlexPod es una infraestructura integrada líder que admite una amplia gama de cargas de trabajo empresariales y casos prácticos. Esta solución le permite poner en marcha SAP HANA de forma rápida y fiable con un modelo de modo de integración de centro de datos personalizado.

La arquitectura de la solución recomendada se basa en Cisco Unified Computing System (Cisco UCS) mediante una versión de software unificada para admitir las plataformas de hardware de Cisco UCS que incluyen los siguientes componentes:

* Los servidores blade Cisco UCS B-Series y los servidores de montaje en rack Cisco UCS C-Series configurables con la opción Intel Optane Data Center Persistent Memory Module (DCPMM)
* Interconexiones de estructuras Cisco UCS de la serie 6300
* Switches Cisco Nexus 9000 Series
* Cabinas de almacenamiento All Flash Series de NetApp


Además, este documento proporciona validaciones tanto para Red Hat Enterprise Linux como para SUSE Linux Enterprise Server para SAP HANA.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_sap_netappaffa_design.html["FlexPod Datacenter para la solución SAP con Cisco UCS Manager 4,0 y NetApp AFF A–Series: Diseño"^]
