---
sidebar: sidebar 
permalink: ent-db/fpd-sap-afa-design.html 
keywords: flexpod, cisco, sap, hana, ucs, aff, a-series, tdi 
summary: 'Este documento describe la solución FlexPod de Cisco y NetApp, la cual es un enfoque validado para la puesta en marcha de entornos de integración personalizada del centro de datos (TDI) de SAP HANA.' 
---
= FlexPod Datacenter para la solución SAP con Cisco UCS Manager 4,0 y NetApp AFF A–Series: Diseño
:allow-uri-read: 


Pramod Ramamurthy, Cisco Marco Schoen, NetApp

Este documento describe la solución FlexPod de Cisco y NetApp, la cual es un enfoque validado para la puesta en marcha de entornos de integración personalizada del centro de datos (TDI) de SAP HANA. Este diseño validado proporciona directrices y un marco para implementar SAP HANA con prácticas recomendadas de Cisco y NetApp.

FlexPod es una infraestructura integrada líder que admite una amplia gama de cargas de trabajo empresariales y casos prácticos. Esta solución le permite poner en marcha SAP HANA de forma rápida y fiable con un modelo de modo de integración de centro de datos personalizado.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_sap_netappaffa_design.html["FlexPod Datacenter para la solución SAP con Cisco UCS Manager 4,0 y NetApp AFF A–Series: Diseño"^]
