---
sidebar: sidebar 
permalink: ent-db/fpd-sap-cisco-aci-deploy.html 
keywords: flexpod, cisco, sap, hana, ucs, aff, a-series, aci 
summary: Este documento describe los procedimientos de arquitectura y puesta en marcha para la opción de integración personalizada del centro de datos de SAP HANA en la infraestructura de FlexPod 
---
= FlexPod Datacenter para SAP con Cisco ACI, Cisco UCS Manager 4,0 y AFF A-Series de NetApp: Puesta en marcha
:allow-uri-read: 


Pramod Ramamurthy, Cisco Marco Schoen, NetApp

[role="lead"]
En este documento se describen los procedimientos de arquitectura y puesta en marcha para la opción de integración personalizada del centro de datos de SAP HANA en la infraestructura de FlexPod, la cual consta de:

* Cisco UCS Computing System (Cisco UCS) compatible con procesadores escalables Intel Xeon de segunda generación.
* Cambiar productos que aprovechan la infraestructura centrada en aplicaciones (ACI) de Cisco.
* Cabinas AFF A-Series de NetApp.


El objetivo de este documento es mostrar los pasos de configuración detallados para la implementación de SAP HANA

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_ACI_sap_netappaffa.html["FlexPod Datacenter para SAP con Cisco ACI, Cisco UCS Manager 4,0 y AFF A-Series de NetApp: Puesta en marcha"^]
