---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_use_cases.html 
keywords: netapp, ontap, cisco, intersight, storage, use cases, monitor, monitoring, orchestration, reference workflows, custom workflows, storage inventory, widgets 
summary: Estos son algunos ejemplos de casos de uso para la supervisión y la orquestación del almacenamiento de NetApp de Cisco Intersight. 
---
= Casos de uso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Estos son algunos ejemplos de casos de uso para la supervisión y la orquestación del almacenamiento de NetApp de Cisco Intersight.



== Caso de uso 1: Supervisión del inventario y los widgets de almacenamiento de NetApp

Si el entorno de almacenamiento de NetApp está disponible en Cisco Interview, puede supervisar los objetos de almacenamiento de NetApp de forma detallada desde el inventario de almacenamiento y obtener una descripción general de los widgets de almacenamiento.

. Implemente el OVA de Intersight Assist (tarea OnPrem en el entorno de vCenter).
. Añada dispositivos de mensajería unificada AIQ de NetApp en Intersight Assist.
. Vaya a *Storage* y desplácese por el inventario de almacenamiento de NetApp.
. Añada *Widgets* para almacenamiento de NetApp a su *Panel de monitores*.




== Caso de uso 2: Orquestación de almacenamiento de NetApp mediante flujos de trabajo de referencia

Cuando los entornos de almacenamiento de NetApp y vCenter están disponibles en Cisco Intersight, puede utilizar los flujos de trabajo de referencia integrales disponibles en GitHub a través del https://github.com/ucs-compute-solutions/FlexPod-Intersight-Workflow["Repositorio de flujo de trabajo Intersight de FlexPod"^].

Los flujos de trabajo de referencia incluyen tareas de almacenamiento y virtualización. El archivo README del repositorio proporciona los requisitos previos necesarios para ejecutar flujos de trabajo, enlaces a recursos útiles (incluida la documentación sobre cómo importar un flujo de trabajo) y enlaces de documentación para cada flujo de trabajo de referencia.

Cada flujo de trabajo tiene una carpeta en el repositorio que contiene dos archivos:

* El archivo JSON para descargar e importar a Intersight,
* Archivo de documentación que proporciona una vista de las tareas del flujo de trabajo, entradas del flujo de trabajo y un ejemplo de ejecución del flujo de trabajo.


Realice lo siguiente para importar y utilizar un flujo de trabajo de referencia:

. Implemente el OVA de Intersight Assist (tarea OnPrem en el entorno de vCenter).
. Añada dispositivos de mensajería unificada AIQ de NetApp en Intersight Assist.
. Añada el destino de vCenter a Intersight mediante Intersight Assist.
. Descargue el archivo JSON para obtener un flujo de trabajo de referencia del repositorio de FlexPod-Intersight-Workflow.
. Importe el flujo de trabajo a Intersight y, a continuación, ejecute el flujo de trabajo.


La siguiente es una lista de flujos de trabajo disponibles en el repositorio de GitHub FlexPod-Intersight-Workflow:

* Agregue iniciadores al iGroup de NetApp
* Nueva política de exportación para volúmenes de NetApp
* Nuevo almacén de datos NAS con el volumen inteligente de NetApp
* Nueva interfaz de datos de FC NetApp
* Nuevo iGroup de NetApp
* Nueva interfaz de datos de iSCSI de NetApp
* Nueva interfaz de datos NAS de NetApp
* Nuevo equipo virtual de almacenamiento de NetApp
* Nuevo almacén de datos de VMFS mediante la Smart LUN de NetApp
* Quite los iniciadores del iGroup de NetApp
* Elimine el almacén de datos NAS con el volumen inteligente de NetApp
* Eliminar Política de exportación de NetApp
* Quite el iGroup de NetApp
* Elimine el almacén de datos de VMFS mediante la Smart LUN de NetApp
* Actualice el almacén de datos NAS con el volumen inteligente de NetApp
* Actualice el almacén de datos de VMFS mediante la Smart LUN de NetApp




== Caso de uso 3: Flujos de trabajo personalizados utilizando un formulario sin diseñador

Cuando haya disponibles los entornos de almacenamiento de NetApp y vCenter en Cisco Intersight, puede crear flujos de trabajo personalizados mediante las tareas de virtualización y almacenamiento de NetApp.

. Implemente el OVA de Intersight Assist (tarea OnPrem en el entorno de vCenter)
. Añada dispositivos de mensajería unificada AIQ de NetApp en Intersight Assist.
. Añada un destino de vCenter a Intersight mediante Intersight Assist.
. Desplácese hasta la ficha *orquestación* de Intersight.
. Seleccione *Crear flujo de trabajo*.
. Añada tareas de almacenamiento y virtualización a sus flujos de trabajo.
+
Estas son las tareas de almacenamiento de NetApp que están disponibles en Cisco Intersight:

+
** Añadir ACL a recurso compartido CIFS de NetApp
** Agregar coincidencia de cliente a regla de política de exportación de NetApp
** Añada una política de exportación a volumen NetApp
** Agregue iniciadores al iGroup de NetApp
** Agregar regla a la política de exportación de NetApp
** Agregue programación a la política de snapshot de NetApp
** Confirme el estado de la licencia de NetApp
** Confirme el estado del protocolo FCP de la máquina virtual de almacenamiento NetApp
** Editar agregados de NetApp para la máquina virtual de almacenamiento
** Editar Política de SnapMirror asíncrono de NetApp
** Editar permiso de ACL de uso compartido de CIFS de NetApp
** Editar regla de política de exportación de NetApp
** Editar política de snapshot de NetApp
** Editar la programación de política de snapshots de NetApp
** Editar el estilo de seguridad del volumen NetApp
** Editar la política de snapshots de volumen NetApp
** Habilite los servicios CIFS de NetApp
** Expanda NetApp LUN
** Nueva Política de SnapMirror asíncrono de NetApp
** Nuevo servidor CIFS de NetApp
** Nuevo recurso compartido CIFS de NetApp
** Busque Mapa de LUN de iGroup de NetApp
** Busque LUN de NetApp por ID
** Busque Volumen NetApp por ID
** Nueva política de exportación de NetApp
** Nueva interfaz de datos de FC NetApp
** Nuevo iGroup de NetApp
** Nueva interfaz de datos de iSCSI de NetApp
** Nuevos reflejos de uso compartido de carga de NetApp para el volumen raíz de SVM
** Nuevo LUN de NetApp
** Nuevo mapa de LUN de NetApp
** Nueva interfaz de datos NAS de NetApp
** Nuevo volumen inteligente NAS de NetApp
** Nuevo Smart LUN de NetApp
** Nueva relación de SnapMirror de NetApp para volumen
** Nueva política de copias Snapshot de NetApp
** Nuevo equipo virtual de almacenamiento de NetApp
** Nuevo volumen NetApp
** Nueva snapshot de volúmenes de NetApp
** Registrar DNS para la máquina virtual de almacenamiento de NetApp
** Eliminar ACL del recurso compartido CIFS de NetApp
** Eliminar coincidencia de cliente de regla de política de exportación de NetApp
** Quite la política de exportación de volúmenes NetApp
** Quite el iniciador del iGroup de NetApp
** Quite el servidor CIFS de NetApp
** Eliminar el recurso compartido CIFS de NetApp
** Eliminar Política de exportación de NetApp
** Quite la interfaz de datos de FC de NetApp
** Quite el iGroup de NetApp
** Elimine la interfaz IP de NetApp
** Elimine los reflejos de uso compartido de carga de NetApp para el volumen raíz de SVM
** Quite la LUN de NetApp
** Quite Mapa de LUN de NetApp
** Elimine el volumen inteligente del NAS de NetApp
** Eliminar NetApp Smart LUN
** Quite la relación de SnapMirror de NetApp para volumen
** Quitar la política de SnapMirror de NetApp
** Eliminar la política de snapshot de NetApp
** Quitar la máquina virtual de almacenamiento de NetApp
** Quite el volumen NetApp
** Quite una snapshot de volumen NetApp
** Eliminar regla de la política de exportación de NetApp
** Quitar programación de la política de snapshots de NetApp
** Cambie el nombre de NetApp Volume Snapshot
** Actualice los reflejos de uso compartido de carga de NetApp para el volumen raíz de SVM
** Actualice la capacidad del volumen NetApp



