---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: Compruebe que cumple los requisitos de hardware, software y licencia de la integración del almacenamiento de ONTAP de NetApp con Cisco Intersight. 
---
= Requisitos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Compruebe que cumple los requisitos de hardware, software y licencias para la integración del almacenamiento de NetApp ONTAP con Cisco Intersight.



== Requisitos de hardware y software

Estos son los componentes mínimos de hardware y software necesarios para implementar la solución. Los componentes que se usan en cualquier implementación particular de la solución pueden variar en función de las necesidades del cliente.

|===
| Componente | Detalles de los requisitos 


| ONTAP de NetApp | ONTAP 9.7P1 y posterior 


| Active IQ Unified Manager de NetApp | Se requiere la última versión de NetApp Active IQ Unified Manager (actualmente 9.14RC1) 


| Cabina de almacenamiento NetApp | Cabinas de almacenamiento All ONTAP ASA, AFF y FAS compatibles con ONTAP 9.7P1 y versiones posteriores 


| Hipervisor de virtualización | VSphere 7,0 y versiones posteriores 
|===

NOTE: Consulte https://intersight.com/help/saas/supported_systems["Sistemas compatibles con Cisco Intersight"^] Para ver los requisitos mínimos de los componentes de computación de Cisco UCS y la versión UCSM.



== Requisitos para la licencia de Cisco Intersight

Cisco Intersight ofrece servicios como el servicio de infraestructura y el servicio Cloud Orchestrator para gestionar, automatizar y optimizar el almacenamiento físico (almacenamiento de NetApp). Puede utilizar estos servicios para gestionar el servidor Cisco UCS y el sistema Cisco HyperFlex. El servicio Infrastructure Service y Cloud Orchestrator utilizan un modelo de licencias basado en suscripción con varios niveles. Puede seleccionar el nivel de volumen de Cisco UCS Server necesario para el período de suscripción seleccionado.

.Modelo de licencia
Se ha simplificado el modelo de licencias de Cisco Intersight Infrastructure Services y ahora ofrece los siguientes dos niveles:

* *Cisco Intersight Infrastructure Services Essentials* - El nivel de licencia Essentials ofrece gestión de servidores, incluida la funcionalidad de monitoreo de estado global, inventario, soporte proactivo a través de la integración de Cisco TAC, autenticación multifactor, además de proporcionar acceso a SDK y API.
* * Cisco Intersight Infrastructure Services Advantage* - El nivel de licencia Advantage ofrece una gestión avanzada de servidores con visibilidad extendida, integración de ecosistemas, automatización de Cisco y hardware y software de terceros, además de proporcionar soluciones multidominio.


Para obtener más información acerca de las funciones cubiertas por los distintos niveles de licencia, vaya a. https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model["Licencia de servicios de infraestructura"^].
